### ISSUE TITLE
TumblrThree cannot import datas from flagged posts "as NSFW"

### ISSUE THREAD

**Issue by amorakfd** [TumblThreeApp/TumblThree#1]
Since january 3rd, TumblThree is no longer able to find any data from flagged as explicit posts, it looks like these posts don't exist anymore. The total number of posts appearing in [number of downloads] column before crawling is correct, but these posts are missing, no infos neither in images, images_url or texts files after backup. Please, do you know a solution? Thank you for your help.

**Comment by thomas694** [comment]
watchers:
[object Object]
stargazers:
[object Object]
