### ISSUE TITLE
The 32bit app is downloading the wrong zip file

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#100]
**Describe the bug**
When checking for updates in the About dialog, the app always downloads the 64bit version zip file even if the running app is 32bit. The app doesn't check if the running process is 64/32 bit and/or takes the wrong download link.

**To Reproduce**
1. Start the 32bit version
2. Go to About dialog
3. Click on 'Check for update'
4. Check the filename of the downloading zip

**Expected behavior**
If the 32bit version is running, I expect the 32bit zip file to be downloaded.

**Desktop (please complete the following information):**
 - TumblThree version: 1.0.11.12
 - OS: Windows 10

Who is able to find the problem? Can you solve it?

**Comment by thomas694** [comment]
This one is for first-timers-only. That means that we will only accept a PR for this one from someone who's never contributed to open source before. This one is particularly easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). We walk you through it if you need help. :-) Here are the steps to get a PR merged here (see also our [wiki](https://github.com/TumblThreeApp/TumblThree/wiki/How-to-Open-a-TumblThree-Pull-Request)).

- [x] Create a fork of the repository
- [x] Clone it to your local disk and create a new branch (e.g. *100-download-correct-zip-file*)
- [x] You should inspect around [line 41](https://github.com/TumblThreeApp/TumblThree/blob/5358ebd9a0925f0b157f94e499dfb0ce89123412/src/TumblThree/TumblThree.Applications/Services/ApplicationUpdateService.cs#L41) in ApplicationUpdateService.cs in folder Services of the project TumblThree.Applications.
- [x] You need to find out if the currently running app/process is running under 64bit (Is64BitProcess) *Environment* or not
- [x] You need to find out which *descendant* child node "browser_download_url" contains "x64-App" or "x86-App" in its url and assign that one to the variable "downloadLink"
- [x] Commit your changes mentioning "issue #100" in the comment
- [x] Push your changes to your fork, create a PR, get merged, celebrate ??

We are happy to support you if you need help.

**Comment by thomas694** [comment]
This one is for first-timers-only. That means that we will only accept a PR for this one from someone who's never contributed to open source before. This one is particularly easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). We walk you through it if you need help. :-) Here are the steps to get a PR merged here (see also our [wiki](https://github.com/TumblThreeApp/TumblThree/blob/master/Contributing.md)).

- [x] Create a fork of the repository
- [x] Clone it to your local disk and create a new branch (e.g. 100-download-correct-zip-file)
- [x] You should inspect around [line 41](https://github.com/TumblThreeApp/TumblThree/blob/5358ebd9a0925f0b157f94e499dfb0ce89123412/src/TumblThree/TumblThree.Applications/Services/ApplicationUpdateService.cs#L41) in ApplicationUpdateService.cs in folder Services of the project TumblThree.Applications.
- [x] You need to find out if the currently running app/process is running under 64bit (*Is64BitProcess*) *Environment* or not
- [x] You need to find out which *descendant* child node "browser_download_url" contains "x64-App" or "x86-App" in its url and assign that one to the variable "downloadLink"
- [x] Commit your changes mentioning "issue #100" in the comment
- [x] Push your changes to your fork, create a PR, get merged, celebrate ??

We are happy to support you if you need help.

**Comment by khintze1** [comment]
Could I please take this!  First timer here :-)

**Comment by thomas694** [comment]
Thanks for your interest. I'll assign that one to you.
Please ask if you have a question or get stuck.

**Comment by KasperLarssen** [comment]
If this one gets free, I am ready to give it a go. First time contributer for open source

**Comment by thomas694** [comment]
Thanks for your interest. Keep an eye on the issue, or maybe try to solve one of the other open issues.

**Comment by khintze1** [comment]
@thomas694  I was able to add the Is64bit.  However, I feel like I'm over complicating the next step.  Looking at this page https://api.github.com/repos/tumblthreeapp/tumblthree/releases/latest I can see the browser_download_url is different for each version, but I'm not seeing any other node that would make it easy to know which one to assign.  Should I be doing a search on the name to find one with 64 or 86?  Or is there something easier I'm missing?
Sorry if this is a dumb question.  Total newbie here.

**Comment by thomas694** [comment]
We are currently using this pattern for naming the release files: {ProductName}-{VersionString}-{Bitness}-{PackageType}.zip
Yes, as this release json is done by GitHub and there's no better or unique field, you just have to search the browser_download_url fields for a string part "x64-App" or "x86-App" (ideally case-insensitive). In the case the code shouldn't find an entry, it should use the first entry like it's done currently.
Better to ask an easy question than spending too long searching for a way too complicated answer.

**Comment by thomas694** [comment]
@khintze1 If you have any other question, please feel free to ask me.

**Comment by khintze1** [comment]
@thomas694 I was thinking of doing something like this 
http://csharp.net-informations.com/xml/search-in-xml-file.htm
is that the right path?

**Comment by thomas694** [comment]
@khintze1 I think you lost a bit your way, that's not really the right page you found.
You can work with the *XElement* object which now contains a xml representation of the json string we downloaded before. And you have to find a way to *filter* the nodes by *element name* (browser_download_url).
While working with the XElement object, you can either use LINQ methods or do it old-fashioned.

**Comment by khintze1** [comment]
So I think I pushed it to the branch if you want to take a look?

**Comment by thomas694** [comment]
You're going into the right direction...
In the else-branch you have overlooked to put curly braces. Without them, it won't do what you're expecting, even you've indented your code. In the following I pretended they are there.
Besides if the code is like here, you can put every line which is in both branches of the if statement in front of the if. It prevents code duplication and makes it more readable.
Does your code compile? Have you tested your code, either by letting the app download the json or using a temporary debug construct like the following? 
```
string str = @"{copy the json text here}";
StringReader sr = new StringReader(str);
XElement root = XElement.Load(sr);
```
I think you could find a method (inside XElement) that returns more than one element (with the searched element name) at once, so that you can apply `Where` to it and check if one of the *element*'s *Value* *Contains* the searched string. You also don't have to care on which level of the xml structure the browser_download_url nodes are, as they are "unique" enough.
If I expressed myself unclear or you have any question, let me know.

**Comment by khintze1** [comment]
OK round two.  Thanks so much for all of your help!!  I really appreciate it.  Let me know if that was more what you were looking for.  Which file should I try compiling to see if it works?

**Comment by thomas694** [comment]
Yes, you fixed the first two points and now it looks better than before.
Just build the whole solution in Visual Studio. If there are errors in your code, it will show you in the errors window.
If the solution is built without errors, you can put a breakpoint on e.g. [line 36](https://github.com/khintze1/TumblThree/blob/dba702254c4c8372b6d7319e48f2ca6c6b1b2b5c/src/TumblThree/TumblThree.Applications/Services/ApplicationUpdateService.cs#L36) and run the app in debug mode. Check for an update version in the about dialog and the debugger stops on that line. Now you can inspect the content of the variables by hoovering over them or using the QuickWatch window. QuickWatch can also be used with partial marked lines, e.g. `root.Element("assets")` or `root.Element("assets").Element("item").Element("browser_download_url")`.
Does your code work?

**Comment by khintze1** [comment]
I think I'm really close now.  This one compiles.  The only issue I'm having is I can't get it to write the value back to downloadlink variable.  It currently fails because it's not set to an instance of an object.

**Comment by thomas694** [comment]
Well, you're much closer, but still something missing.
Did you set breakpoints and look what the values are which have been returned? I assume not.

`Where` doesn't find any nodes, so the `foreach` loop can't iterate any elements in `query` and assign a value to `downloadLink`. That's why you see a 'not set to an instance of an object' failure.
Which elements does `Elements()` return? "Returns a collection of the child elements of this element or document, in document order". Where are the `browser_download_url` nodes compared to the root node? Does the root (XElement class) have another method (also look on its overloads) that suits better (returning every node below root at once)?

Later when you find the correct nodes, you have to improve your filter. Are you looking for anything containing "x64-App" or a `browser_download_url` node which contains "x64-App"? That's a difference. Look on the [release file](https://api.github.com/repos/tumblthreeapp/tumblthree/releases/latest) again, whether it's json or xml doesn't matter for that, the levels are the same.

At the end, if you still keep that line, you should use `downloadLink = element.Value;`. The output is different.

**Comment by khintze1** [comment]
Alright, I think I have the right nodes?  Does the elements return just the values in the browser_download_url?  So what is there works for 64 bit, but not for 32 bit in testing.  In the 32 bit it goes back to the null error.  Is it just a fluke that the 64 bit one is working?

**Comment by thomas694** [comment]
Your variable `elements` returns nodes. But for assignment to `downloadLink` you need the node's value, the url string. You can test/simulate both cases, either (temporarily) negate your if condition or set the breakpoint line in the else block when the debugger stops on your breakpoint at the if statement. For both cases the `downloadLink` variable should be set correctly and the downloaded zip file should be the x86 or x64 one.
But your 32 bit code is not giving you the right thing, because you used `root.Element("assets").Element("item").Element("browser_download_url")` again like before (see above). That's returning always the first item on every level, in our release json that's the "x64-App" one.
To solve it, you can e.g. use a for-loop on every level to go through all the nodes and search the right one, or you just find another method which does that for you. Please take a look at [MS Docs - XElement Class](https://docs.microsoft.com/en-us/dotnet/api/system.xml.linq.xelement?view=netframework-4.6.2#methods). Which method can give back all child nodes regardless of the level and at the same time filter for the desired node name ("XName", here "browser_download_url")?

**Comment by khintze1** [comment]
Ok so I finally got it :-) I needed to go through the descendants not elements :-)  In the debug one I have tested that it works for 64 and 32 bit and gets the correct download link.

**Comment by thomas694** [comment]
That's great. :-) Your answer is working (and accepted).

But we should polish your code a bit. You like?
Actually you used the chained method `Where` (your point at the end of previous line) and not the `Linq Where`, so actually it means, take every element of `IEnumerable<XElement>` and return them as `IEnumerable<XElement>`:
```
IEnumerable<XElement> elements =
                          from el in {IEnumerable<XElement>}
                          select el;
```
As Descendants() and Where() already return `IEnumerable<XElement>` that step is unnecessary, so just use the inner one (*1):
```
IEnumerable<XElement> elements = root.Descendants("browser_download_url").Where(s => s.Value.Contains("x64-App"));
// Linq where would be:  where el.Value.Contains("x64-App")
```
Your for-loop is ok, but C# has a new ["null-conditional operator"](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-), so you could shorten it:
```
downloadLink = elements.FirstOrDefault()?.Value;
```
At the end you could even combine all in one line:
```
downloadLink = root.Descendants("browser_download_url").Where(s => s.Value.Contains("x64-App")).FirstOrDefault()?.Value;
```

After your if-else statement, it would be good, if the first found entry would be assigned (like in the old code). Just in case the deployment is changed in the future without updating this method, it would still give back the first download link (*2):
```
if (string.IsNullOrEmpty(downloadLink)) downloadLink = root.Element("assets").Element("item").Element("browser_download_url").Value;
```
Please adapt at least *1 and *2. Then create your pull request.

**Comment by khintze1** [comment]
So in the end, I shortened it to this:
//IEnumerable<XElement> elements = root.Descendants("browser_download_url").Where(s => s.Value.Contains("x86-App"));
                   
 downloadLink = root.Descendants("browser_download_url").Where(s => s.Value.Contains("x86-App")).FirstOrDefault()?.Value;

I don't even need the for loop or the first line do I?

I also added the ending part.

**Comment by thomas694** [comment]
Yes, you can shorten it to one line. One line for each part of your if-else statement (x86/x64).

**Comment by thomas694** [comment]
Thanks for your first contribution and PR to open source, and especially to the TumblThree project.
Your PR has been merged and you've been added to our list of contributors.
You are welcome to solve some more issues (not first-timers-only).
