### ISSUE TITLE
Can not download a specific tumblr anymore

### ISSUE THREAD

**Issue by HydroHydro** [TumblThreeApp/TumblThree#101]
**Describe the bug**
This tumblr used to work a few months ago: https://protobacillus.tumblr.com/
But now it fails.

**To Reproduce**
1. Add https://protobacillus.tumblr.com/
2. Try to Crawl.
3. Nothing happens.

**Expected behavior**
It should start downloading.

**Desktop (please complete the following information):**
 - TumblThree version: 1.0.11.12
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
Alternative URL: https://www.protobacillus.com/
Also doesn't work anymore.

**Comment by thomas694** [comment]
Thanks for your bug report and providing an example url. At least it should be possible to add the blog by using the tumblr subdomain.

**Comment by thomas694** [comment]
[As before](https://github.com/TumblThreeApp/TumblThree/issues/99) this one is for first-timers-only. That means that we will only accept a PR for this one from someone who's never contributed to open source before. This one is particularly easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). We walk you through it if you need help. :-) Here are the steps to get a PR merged here (see also our [wiki](https://github.com/TumblThreeApp/TumblThree/blob/master/docs/Contributing.md)).

- [x] Create a fork of the repository
- [x] Clone it to your local disk and create a new branch (e.g. 101-fix-blog-download-problem)
- [x] Build the app and run it in debug mode of VS
- [x] Set a breakpoint in [line 114](https://github.com/TumblThreeApp/TumblThree/blob/ce7a675a9e2a74ab135ed24b72b6653567ec0f43/src/TumblThree/TumblThree.Applications/Crawler/TumblrBlogCrawler.cs#L114) of TumblrBlogCrawler.cs
- [x] Try to add the above blog (with its tumblr url), step through the code and find the problem
- [x] You should come to the conclusion that the problem has to do with [line 149](https://github.com/TumblThreeApp/TumblThree/blob/ce7a675a9e2a74ab135ed24b72b6653567ec0f43/src/TumblThree/TumblThree.Applications/Services/WebRequestFactory.cs#L149) in WebRequestFactory.cs and [line 125](https://github.com/TumblThreeApp/TumblThree/blob/ce7a675a9e2a74ab135ed24b72b6653567ec0f43/src/TumblThree/TumblThree.Applications/Crawler/AbstractCrawler.cs#L125) in AbstractCrawler.cs. What exactly is the problem? For this blog another kind of redirect is requested in the response header.
- [x] What has to be done to solve the problem? Does the solution also solve it for the other crawlers?
- [x] Commit your changes mentioning "issue #101" in the commit message
- [x] Push your changes to your fork, create a PR, get merged, celebrate ??

We are happy to support you if you need help.

**Comment by xinwhyi** [comment]
Hello, first timer here. May I try fix this issue?

**Comment by thomas694** [comment]
Hello,
thanks for your interest. Yes, you can work on that issue. I'll assign it to you.
If you have a question or get stuck, feel free to ask.

**Comment by xinwhyi** [comment]
VS prompts the project can only run on VS Windows, does that sound right? If so, I'm afraid I can't take this issue :(

**Comment by thomas694** [comment]
Yes, TumblThree is a Windows application. That's no problem, I'll unassign the issue.
So this issue is free for someone else.

**Comment by arrowsmith001** [comment]
Hi, I would like to have a go at this issue.

**Comment by thomas694** [comment]
Ok, here you go.

**Comment by thomas694** [comment]
Thank you for your first contribution and PR to our TumblThree project.
Your PR has been merged and you've been added to our list of contributors.
We would be happy to receive more contributions from you in the future. Maybe you can help us with one or the other issue.
