### ISSUE TITLE
New column with timestamp of latest post

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#103]
**Is your feature request related to a problem? Please describe.**
It's difficult to see in the blog list, if a blog is stale for a period of time and can be removed because there's no more activity.
The column "Last Complete Crawl" isn't helpful for that. It only shows the last time the crawler run, whether there has been fresh content downloaded or not.

**Describe the solution you'd like**
Another column that shows the timestamp of the most recent blog post.

**Comment by ErikBrown2** [comment]
That would indeed be a nice additional feature.
