### ISSUE TITLE
How to get photosets to save together?

### ISSUE THREAD

**Issue by kyuber** [TumblThreeApp/TumblThree#104]
Similar to an issue previously reported, the files are saving as random strings of letters and numbers, rather than the previous tumblr_XXX, which in turn has photos that are originally in photosets no longer side by side in the folder and no longer in the same order that they were on the blog. Is there a way to fix this in the settings?

**Comment by thomas694** [comment]
Thanks for reporting an issue. Can you provide an appropiate example post?
Currently there is no way or a setting to fix under which filenames the images are saved.

**Comment by thomas694** [comment]
maybe related to the problem in issue #56

**Comment by thomas694** [comment]
The issue has been fixed (see #56) and closed.
