### ISSUE TITLE
Save downloaded media with post date as modification timestamp

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#111]
**Expected Behaviour**

When crawling a blog that contains posts with inlined media (e.g. html in the post), the image and video files should have the modification timestamp of the original post date too.

**Actual Behaviour**

The images and videos are saved with the current date and time.

**Steps to Reproduce the Problem**

  1. Download a blog with several blog entries over a period of time
  2. After the download has finished, check the file timestamps.

**Specifications**

current TumblThree version

**Comment by arrowsmith001** [comment]
Hi @thomas694. I want to have a go at this issue. Could you please give me an example of what you mean by "inlined media" and how I would create such a post as a tumblr user? Thanks.

**Comment by thomas694** [comment]
Hi, sure.
I've never created such a post myself, but I think the steps are like that: you can start with a text post, then change their editor to html mode and insert img tags with links to either images hosted on tumblr servers or to external urls. So when you look at the downloaded post's json representation, the post's "image array" is not filled, but only the post's text field contains html showing the images. TumblThree can parse these image urls out of the text field's html and download them.
I should have saved the url as an example at that time.

**Comment by thomas694** [comment]
Thanks for taking care of this issue.
