### ISSUE TITLE
Adding a non-existing or no longer existing blog silently fails

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#112]
**Describe the bug**
Adding a non-existing or no longer existing blog silently fails without error message or the like.

**To Reproduce**
1. Enter a no longer existing blog address in the url field (e.g. urmeimu.tumblr.com)
2. Click on 'Add Blog'
3. Nothing visible happens

**Expected behavior**
At least a message should be shown, some error label, a log entry or the like.

**Desktop (please complete the following information):**
 - TumblThree version: 1.0.11.13
 - OS: Windows 10
 - Browser: Chrome

**Additional context**

**Comment by thomas694** [comment]
[As before](https://github.com/TumblThreeApp/TumblThree/issues/98) this one is for first-timers-only. That means that we will only accept a PR for this one from someone who's never contributed to open source before. This one is particularly easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). We walk you through it if you need help. :-) Here are the steps to get a PR merged (see also our [guide](https://github.com/TumblThreeApp/TumblThree/blob/master/Contributing.md)).

When trying to add a non-existing or no longer existing blog to TumblThree, nothing visible happens, no error message is shown and the blog is not added to the blog list. But the blog's database file and download directory are already created. The problem is that the blog cannot be added because it just don't exist. So a message in the error message bar should be shown to the user. Additionally it either should be prevented that the file and directory are created or they should be cleaned up afterwards.

- [x] Create a fork of the repository
- [x] Clone it to your local disk and create a new branch (e.g. 112-adding-non-existing-blog-fails)
- [x] Look what class and methods are used to add a new blog inside the TumblThree.Applications project. Does it look more easy to prevent the file and directory creation or to remove it afterwards? How can the code be changed to accomplish it?
- [x] Add your solution
- [x] Build the app and run it
- [x] Type in the url of a non-existing blog and try to add it
- [x] Check if your error message occurs
- [x] Commit your changes mentioning "issue #112" somewhere in your commit message title or description
- [x] Push your changes to your fork, create a PR, get merged, celebrate??

We are happy to support you if you need help.

**Comment by divyanshmishra19** [comment]
Has this been taken up? I'm contributing to open source for the first time but this looks like a good place to start

**Comment by thomas694** [comment]
Hello,
thanks for your interest to work on this issue. It is free and I will assign it to you.
Please ask if you have a question or get stuck.

**Comment by thomas694** [comment]
Do you need any help?

**Comment by arrowsmith001** [comment]
Hi. I'm interested in contributing to open source for the first time and I'd give this problem a good go. Would you be willing to reassign this to me?

**Comment by thomas694** [comment]
Hello,
thanks for your interest to work on this issue. As we haven't received any reaction for over 14 days (e.g. asking for more time), according to our rules, this issue can be reassigned.
I assign it to you.

**Comment by arrowsmith001** [comment]
I could not reproduce the issue. Entering the example URL and pressing "Add Blog" resulted in an error message, as shown.

![Capture](https://user-images.githubusercontent.com/68137859/111886798-72f42700-89c8-11eb-8cd1-c792e699e503.PNG)

**Comment by thomas694** [comment]
Oops, I double checked, it slipped in with the last version. So it's already solved.
Can you please tackle one of the other open issues?

**Comment by thomas694** [comment]
The issue has been fixed and closed.
