### ISSUE TITLE
0 Byte files?

### ISSUE THREAD

**Issue by NikAWing** [TumblThreeApp/TumblThree#114]
Hello :)

Just trying to find out if something changed:
I use TumbleThree for a long time now, but recently all I get are empty files, any tumblr blog.
It's also not a problem of the x64 version, I kept the old version and it happens there too.
I'm also logged in to tumblr.

Is there a problem with tumblr since a few weeks or is it just me (who changed nothing else)?

 - TumblThree version: 1.0.11.13
 - OS: [e.g. Windows 7 ultimate
 - Browser: hm, newest FF is installed

Thanks for a hint :)

**Comment by thomas694** [comment]
Hello

TumblThree works well here, but I use Win 10.
You can look in the windows event log or in TumblThree log file for a hint. The log file should be in %LOCALAPPDATA%\TumblThree or inside the program folder for portable mode.

We didn't hear of a general problem yet. Who else has Win 7? Does it work to you?

**Comment by NikAWing** [comment]
I also wonder since the "old version" of TT also creates 0 Byte files, so I thought it would be a tumblr problem (I expected they changed the API or something else)

The old version is 1.0.11.8

Any newer TT version won't alter any relevant files, right? I think about the files in the "Index" folder containing settings for each blog. IOW, I can run 1.0.11.8 and any newer release without running into problems, right?

The log file in %LOCALAPPDATA%\TumblThree is empty.
I don't see anything in the Windows event log.

I can't think of any reason why it won't work with Win7 suddenly and I never had any problem with TT before :)

(just a side note: I wished there would be support for newTumbl, but I suppose this one is not easy to solve.)

**Comment by thomas694** [comment]
Yes, version 1.0.11.8 and newer have the same file formats, so no problem. But as you already found out, the old versions show the same behavior, so you can also keep the newest version.

I have no clue what could be the problem. If you want, you can use the newest version and try to get a log file by the way described [here](https://github.com/TumblThreeApp/TumblThree/issues/21#issuecomment-699618439).

**Comment by NikAWing** [comment]
ok, just tried this (added the lines to the config file), but nothing happens? No logfile was created.
Also, no new log in %LOCALAPPDATA%\TumblThree

**Comment by Hrxn** [comment]
Just a wild guess, but have you checked that there's still enough free space on the storage device?

**Comment by NikAWing** [comment]
yes, of course :)
(I would be a complete noob if not, lol)
The only thing I altered on my setup was unpacking the new TumblThree release. I went to the blog list, added a blog to the queue and started the download. I usually monitor the download folder after starting the queue and there I saw that every file has 0 bytes except the txt file (I currently don't know which).
I even made sure to be logged in to tumbler in TTA the settings.
Weird, that it only happens here, isn't it? :o

**Comment by NikAWing** [comment]
ok, while not yet being able to use the newest release I tried downloading files with 1.0.11.13 again to see if it's still not downloading.
The files have content again! So this must have been a problem with tumblr, I did not change anything since the last time I posted here :)

**Comment by thomas694** [comment]
Thanks for the information. It's good to hear it is working now.

Maybe you like to update to the newest version.

**Comment by NikAWing** [comment]
that I currently try to do :)
but since this problem here disappeared, I close the issue now
