### ISSUE TITLE
White window, cannot log in, nothing works

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#115]
Issue #81 hasn't been fixed, cannot log in, nothing works

![](https://cdn.discordapp.com/attachments/604172693633499136/793628256284704778/unknown.png)

I assume there's meant to be something there.

_Originally posted by @teenangst in https://github.com/TumblThreeApp/TumblThree/issues/81#issuecomment-752280691_

**Comment by thomas694** [comment]
This is new issue since some days. The original one was resolved.
_Originally posted by @wacher74 in https://github.com/TumblThreeApp/TumblThree/issues/81#issuecomment-752406590_

@teenangst
Please provide us more information,
so that we can try to find out why it's not working on your system.

What TumblThree version are you using?
Your chrome version?
Did the new login work for you before (until a few days ago)?
Do you have any useful information from windows event log or the log files?

**Comment by wacher74** [comment]
What TumblThree version are you using?
1.0.11.13

Your chrome version?
Microsoft Edge is up to date.
Version 87.0.664.66 (Official build) (64-bit)
and
Google Chrome
Version 87.0.4280.88 (Official Build) (64-bit)
Edge is my default browser

Did the new login work for you before (until a few days ago)?
Last successful day was 26th Dec.

**Comment by wacher74** [comment]
I just updated 1.0.12.0, not working
I'm logged out, but I can't login just to see the big white box

**Comment by thomas694** [comment]
Actually the issue still had to do with issue #81. At that time we had included only the base components of CEF into the release package for saving space and the login process worked. But now again something on the login pages changed and CEF needs an additional component to handle it, but it's not included, so CEF gets stuck with a white window.
So we also add the rest of the components which adds another 5.5MB to the package, but that shouldn't carry weight any more.

**Comment by wacher74** [comment]
It is purring like a kitten, thank you :)
