### ISSUE TITLE
TumblThree crashes unexpectedly while crawling a blog marked NSFW

### ISSUE THREAD

**Issue by Duckxz** [TumblThreeApp/TumblThree#119]
**Describe the bug**
In AbstractDownloader.cs:204 `files` gets referenced but it is null causing a NullReference, crashing the application

**To Reproduce**
1. Build debug version x64 of TumblThree
2. Force the usage of the SVC api
2. Enqueue an NSFW-marked blog 
3. Start crawling
4. Eventually the application will throw a System.NullReferenceException and crash

**Expected behavior**
TumblThree starts downloading the blog media

**Screenshots**
exception message:
![afbeelding](https://user-images.githubusercontent.com/49942153/104909656-7a775f80-5988-11eb-9e3f-363eaa9b084d.png)
call stack:
![afbeelding](https://user-images.githubusercontent.com/49942153/104909743-98dd5b00-5988-11eb-852c-366189d315e2.png)
autos:
![afbeelding](https://user-images.githubusercontent.com/49942153/104909840-c2968200-5988-11eb-9032-f8ad31c601ea.png)

**Desktop**
 - TumblThree version: 1.0.12.2
 - OS: Windows 10
 - Browser Firefox
 - Version 84.0.2

**Additional context**
```
System.NullReferenceException
  HResult=0x80004003
  Message=The object reference is not set to an instance of an object.
  Source=TumblThree.Applications
  StackTrace:
   at TumblThree.Applications.Downloader.AbstractDownloader.<DownloadBlogAsync>d__24.MoveNext() in C:\Users\yamma\Tumblr\TumblThree\source\src\TumblThree\TumblThree.Applications\Downloader\AbstractDownloader.cs:line 204
```

**Comment by thomas694** [comment]
Thanks for your bug report.
The given location isn't the root cause. This object should be passed in CrawlerFactory.cs:79 and be constructed before in CrawlerFactory.cs:62. Are you using the setting LoadAllDatabases? Does the error occur when the blog is added newly or on a second crawl?
If it reaches that location without failing before, it means no files have been downloaded for that blog. Correct?

Do you like to inspect it further?

**Comment by Duckxz** [comment]
> If it reaches that location without failing before, it means no files have been downloaded for that blog. Correct?
This is a second crawl and some files from the blog have already been downloaded

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
