### ISSUE TITLE
Error starting the next item in the queue

### ISSUE THREAD

**Issue by ErikBrown2** [TumblThreeApp/TumblThree#120]
**Describe the bug**
Since the implementation of the preview following the downloaded blogs, sometimes TumbleThree reports the error "Error starting the next item in the queue". After this several queued blogs are highlighted in green and downloading has stopped. So not just the active blog is green but several blogs that were queued are green. The queued items are still in the queue (but all highlighted in green). Today the top item in the queue when it stopped with the error was a search like https://www.tumblr.com/search/xxxx+yyyy but when I ran TumblrThree again with the same queue including the search it worked fine. So I am not sure what triggers the issue.

**To Reproduce**
Not sure what causes it. But it happens when I queue a number of blogs and try to download them.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - TumblThree version: [e.g. 1.0.11.3] TumblThree-v1.1.0.80
 - OS: [e.g. Windows 10 Home] Windows 10 Pro
 - Browser [e.g. Chrome, Safari, IE, Edge] Chrome
 - Version [e.g. 22] Version 87.0.4280.141 (Official Build) (64-bit)

**Additional context**

**Comment by thomas694** [comment]
I'll try find that one in the next days.
At the moment I think the error is shown, but then the same blog is started at the second try.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
