### ISSUE TITLE
Changing multiple blogs from API to SVC causes crash

### ISSUE THREAD

**Issue by MSWallack** [TumblThreeApp/TumblThree#123]
Using v1.2.0.88. After adding several new blogs, I highlight all of them and then change them all from Tumblr API to Tumblr SVC. The program appears to hang for a moment. Clicking anywhere will cause the program to exit (and the change from API to SVC is not saved). I can change blogs from API to SVC individually. Also, this behavior only began in the newest release.

**Comment by MSWallack** [comment]
I've done a bit more testing and the problem seems to occur when trying to bulk update any properties, not just API/SVC. The app crashed when clicking the download reblog posts and the download images boxes.

**Comment by thomas694** [comment]
Thanks for your bug report. I'll look at this in the next days.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
