### ISSUE TITLE
Color cues

### ISSUE THREAD

**Issue by MSWallack** [TumblThreeApp/TumblThree#124]
When a user attempts to add a blog that is already in the list, a blue bar appears on the top of the screen alerting the user that the blog already exists. Similarly, when trying to download blogs, if the blog no longer exists, a blue bar appears at the top of the screen alerting the user. Finally, certain other error messages (timeouts, for example) also appear in a blue bar at the top of the screen.

Would it be possible to distinguish the type of message by color? For example, when a blog no longer exists, rather than use a blue bar, use a red bar. In the case of a timeout, you could use a green or purple bar. This would help a user quickly recognize errors by type, especially when sorting through several messages.

**Comment by thomas694** [comment]
Hello Michael,
that sounds like a nice idea. We should look what different kind of errors could happen and which ones can be grouped together.
Maybe someone would like to take on that issue.

**Comment by MSWallack** [comment]
I'd be happy to take on that issue... but given that I haven't written a line of code (well, other than a macro here and there) since ... um ... well, I was writing in Pascal if that gives you any idea ... I don't think I'm the best guy for the task. Sigh.

**Comment by thomas694** [comment]
Thanks for considering it. I also got to know Pascal... Maybe someone else reads it here and likes to work on it.

**Comment by arrowsmith001** [comment]
I'd be happy to take this up. So, since I have forked the repo already should I just create a new branch from that fork for this issue?

**Comment by thomas694** [comment]
I've assigned it to you. Please have a look.
Yes, just create a new branch.

**Comment by thomas694** [comment]
@arrowsmith001 Thanks for taking care of this issue.
