### ISSUE TITLE
Scrape posts from search results under "Recent" sort

### ISSUE THREAD

**Issue by Muse-2** [TumblThreeApp/TumblThree#125]
**Is your feature request related to a problem? Please describe.**
Trying to scrape the contents of a search always gets posts under the default Popular sort. Attempting to enter a URL such as "https://www.tumblr.com/search/cat/recent" into TumblThree causes the URL to be trimmed to "https://www.tumblr.com/search/cat".

**Describe the solution you'd like**
Entering a URL with Recent sort specified will get posts under that sort, meaning it would get the newest post first, then the second newest, third newest etc. Additionally, maybe give an option to enable or disable Recent sort under "blog settings" or elsewhere.

**Describe alternatives you've considered**
Assuming there is no criteria for a post to be listed under Popular sort, I could imagine that scraping Popular sort would eventually give you all posts under a given search term, just not in order of their original upload date. However, this would cause modified dates to be all over the place, with years old posts being listed as having a newer modified date than something that was posted last week, making it impossible to find what was newly posted without checking the website itself.

**Additional context**
I'm trying to archive posts under a certain search term, and I want to update that archive every day or so. I'm not trying to archive content from a specific creator, and not being able to sort by Recent on search results unfortunately makes this application unfit for my needs. It's a shame that an application this well polished is missing the one feature I require, and I'm hesitant to seek out other applications that may not have the same level of care put into them, so I hope that making this issue will eventually lead to a positive result.

**Comment by thomas694** [comment]
That sounds like a good idea. It should be either possible to enter this kind of urls or to select an option in the blog's settings. I'm not sure but I think it shouldn't take too much changes to get this working.

**Comment by thomas694** [comment]
Now the url field also accepts search urls with the ending "/recent" (e.g. [https://www.tumblr.com/search/cat/recent](https://www.tumblr.com/search/cat/recent)).

For those of you where the Tumblr Search seems not to work after starting. They introduced quite another privacy consent for searches. In the settings beside the login button there is a new button "privacy consent". After clicking on it a browser dialog opens and does a "cat" search. Just confirm the privacy consent and close it. You only have to do that once in a while.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
