### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by elipriaulx** [TumblThreeApp/TumblThree#13]
I'm not sure if there is any sentimental attachment to the current logo and style, but irrespective it would be useful to lock in logos, colours, and general stylistic preferences among those involved early to minimise double handling of the more 'touchy feely' areas. Maybe a style guide or something? Some general consensus of how things should look, feel, and interact with users.

**Comment by johanneszab** [comment]
In case of we want to support other sites, should be rename TumblThree (app as well as organization)? It looks like it's both still possible, and I guess we should do this before releasing anything new.

I'm not particular happy with the name, no do I have any sentimental feelings for it. It was more "logical"/quick decision as I reflected TumblOne once, and just incremented the name to somewhat distinguish it from the original, dead project.

Any suggestions? We can leave it, I really do not care at all.

**Comment by gpriaulx** [comment]
I don't care at all either, and am happy with the TumblThree name. It avoids confusion with existing users at this stage, and offers some history of what led to it coming about. I also like puns, and it kind of has that ring to it. 

Lock it in?

What about logo/styling? I'm no graphic designer, but the logo does look a bit busy to me. Would you be open to moving to something simpler and vector based? I looked at vectorising the existing one but wasn't really sure what was lost in the raster and what wasn't. I know it is petty, but committing to something here would probably offer the rest of the UI stuff a bit of a theme to grow from.
