### ISSUE TITLE
Tumblr Search Offline

### ISSUE THREAD

**Issue by Daulian86** [TumblThreeApp/TumblThree#130]
Hello, I found a Problem with Tumblr Search. 
If I add a Tumblr Search, for example "https://www.tumblr.com/search/car", it shows in the beginning as online, if I check the Online Status or crawl it, the Status will change to offline.

Tested it on two different PCs with Windows 10 Pro, with new downloaded TumblThree. Secound PCs was a fresh Windows 10 Install.

Screenshot:

![Offline](https://user-images.githubusercontent.com/80961217/111785641-2839b880-88bd-11eb-8e15-0225df0e4735.PNG)

Part of the Log, with the Error-Massage I found:

>20210319 13:46:47.096	Err 	AbstractCrawler.RequestDataAsync: System.Net.WebException: Der Remotename konnte nicht aufgelöst werden: 'www.tumblr.comhttps'
   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   bei System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei TumblThree.Applications.Extensions.TaskTimeoutExtension.<TimeoutAfter>d__0`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei TumblThree.Applications.Services.WebRequestFactory.<ReadRequestToEnd2Async>d__13.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei TumblThree.Applications.Crawler.AbstractCrawler.<RequestDataAsync>d__53.MoveNext()

Desktop:
 - TumblThree Version: 1.3.0.96 (64-Bit)
 - OS: Windows 10 Pro (20H2)
 - Browser: Google Chrome
 - Version: 89.0.4389.90 (64-Bit)

It is my first Time posting on github. Hopefully I have posted all necessary information to help.

**Comment by thomas694** [comment]
Thanks for your bug report. Yes, the information is helping us. It looks like a bug which we will fix soon.

Did you already use TumblThree before upgrading to version 20H2 and experienced any problems with it?

**Comment by Daulian86** [comment]
I'm glad that it can help!
I am using TumblThree since roughly 2018, but I didn't use the Search very often. Then with Windows 7 SP1 and now with Windows 10. I tested it today with my old Windows 7 SP1 install, with the same error, just to be sure. I can't remember an error like this prior to 20H2. But as I said before, I didn't use the Search very often. Most cases are entire Blogs and there ware no problems, beside Blogs that went offline, but that's not a software problem, it's a Tumblr problem. :)

**Comment by thomas694** [comment]
It should work again in the newest version.

The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
