### ISSUE TITLE
API connections, error 429

### ISSUE THREAD

**Issue by d0wnl04dr** [TumblThreeApp/TumblThree#141]
As i try to download some Tumblr it appear this error, the program tell to lower the connections in the Settings -> Connection pane. I already disconected the limit of connections but the problem persist.
can you tell me what im doing wrong?
Thanks, and great work

**Comment by thomas694** [comment]
Please see also issue #46.
The default settings normaly work quite well.
In general, you shouldn't use Tumbex or Tumblr in your browser while using a single instance of TumblThree. It's also better to login/authenticate with TumblThree. If you already hit the limit, you can either wait a day or get a new ip address, if possible.

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.
