### ISSUE TITLE
Chocolatey Package for easy install (Windows)

### ISSUE THREAD

**Issue by BrandonKMLee** [TumblThreeApp/TumblThree#142]
Adding the zip file installer to https://chocolatey.org/ would be useful.

**Comment by thomas694** [comment]
We don't think that the normal user is using Chocolatey or wants to install it for keeping our app up-to-date. Also in advertising with main versions on that platform we don't see much advantage.

But we were already thinking about to integrate an auto-updater, so we created another [issue](https://github.com/TumblThreeApp/TumblThree/issues/143) for it now.

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.

**Comment by thomas694** [comment]
For anyone interested in this topic, there is a command-line installer that has our application included:
[Scoop.sh](https://scoop.sh/) / [github.com/ScoopInstaller/Scoop](https://github.com/ScoopInstaller/Scoop)
