### ISSUE TITLE
Crashing to desktop

### ISSUE THREAD

**Issue by TomInVa57** [TumblThreeApp/TumblThree#144]
**Describe the bug**
When enquiringly a blog, the program just exits to the desktop, no error messages displayed. But several errors in Even Log > Applications:
Source - .Net Runtime
Application: TumblThree.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at TumblThree.Applications.Downloader.AbstractDownloader.OnSaveTimedEvent()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()

Source - Application Error:
 Faulting application name: TumblThree.exe, version: 1.4.0.112, time stamp: 0x6066231b
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ff7ad7cd406
Faulting process id: 0x3668
Faulting application start time: 0x01d7345e0fd534f8
Faulting application path: C:\TumblThree\TumblThree.exe
Faulting module path: unknown
Report Id: e81a9093-6237-498a-b1f8-efa0ba363902
Faulting package full name: 
Faulting package-relative application ID:

Source - Windows Error Reporting (there are a number of files attached, but I do not see any option to upload attachments):
Fault bucket 1913437955136127483, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: TumblThree.exe
P2: 1.4.0.112
P3: 6066231b
P4: TumblThree.Applications
P5: 1.4.0.112
P6: 606622f5
P7: 5b1
P8: e
P9: System.NullReferenceException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCA33.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCD51.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCD90.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCD9E.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDDD.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_TumblThree.exe_64f123de4d486eaf74f53b114f0ab3476d234_d508f014_c42a14c1-e09b-41b2-845a-631fcc610423

Analysis symbol: 
Rechecking for solution: 0
Report Id: e81a9093-6237-498a-b1f8-efa0ba363902
Report Status: 268435456
Hashed bucket: c8fb0856624d3e32da8de5aeafa381fb
Cab Guid: 0

**To Reproduce**
Steps to reproduce the behavior: attempting to download photos
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
download photos
**Screenshots**

**Desktop (please complete the following information):**
 - TumblThree version: [e.g. 1.0.11.3] 1.4.0.112
 - OS: [e.g. Windows 10 Home] Windows 10 Pro 64bit (current with all updates)
 - Browser [e.g. Chrome, Safari, IE, Edge] Firefox
 - Version [e.g. 22] 87.0 64bit

**Additional context**
Been using your program for sometime now, really like it, this is the first time i've ever had any issues using it, glad you finally did another update :) If you would like for me to send the files that were added in the Windows Error Report, I would be glad to.
Thank
Mike

**Comment by thomas694** [comment]
Hello Mike,
thanks for reporting the bug.
You could have a look, if there's an entry in our log file (%LOCALAPPDATA%\TumblThree\TumblThree.log). Don't attach the whole file or big parts of it, just the block with the exception leading to this crash, if there is.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
