### ISSUE TITLE
Crash at start -SOLUTION- (not Visual C++)

### ISSUE THREAD

**Issue by Fehertukor** [TumblThreeApp/TumblThree#151]
My program crashed like #148 #147
after trying to upgrade it.
Deleting his folder or upgrading Visual C++ did not help.

**Solution:** 
Deleted Settings folder in %LOCALAPPDATA%\TumblThree
cleaned log manually and saved

For developers! Thank you for you work !

**Comment by thomas694** [comment]
Hello,
thanks for your feedback.
Do you still have backups of the settings folder? If so, you could copy the files one by one to the settings folder (make a backup of your current folder if needed) to see after which one the app no longer starts. Maybe that way we can find out what is the difference which causes these problems.

**Comment by thomas694** [comment]
The newest version 1.5.2 should also work without the workaround.
