### ISSUE TITLE
I can't find the TumblThree.exe file?

### ISSUE THREAD

**Issue by Sara-Abo-Shousha** [TumblThreeApp/TumblThree#153]
like why? i downloaded it from here

**Comment by thomas694** [comment]
The file ("TumblThree-v1.5.2-x64-Application.zip") you downloaded is a zip archive, you have to extract it first. Inside the extracted folder there is the app TumblThree.exe.

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.
