### ISSUE TITLE
Like gone after using the TumbleThree

### ISSUE THREAD

**Issue by smdby** [TumblThreeApp/TumblThree#155]
Hi,

I have more than 2400 likes and yesterday I used TumbleThree. It stopped downloading the likes after 525 from over 2400. Today I tried again and looked into my account ... now I only have 337 likes.
How is that possible?

I have done nothing else to my likes and account.

In case it matters: it is mostly explicit material.

THX
C

**Comment by thomas694** [comment]
Hi,
how old were your likes? Are you sure they all have been still valid? I guess that most of them obviously were already deleted or marked for deletion. It's not immediately updated in every user's likes list.
They are constantly removing explicit blogs.

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.
