### ISSUE TITLE
Not downloading files

### ISSUE THREAD

**Issue by jjdnl** [TumblThreeApp/TumblThree#158]
**Expected Behaviour**

Downloading blogs

**Actual Behaviour**

not downloading anything

**Steps to Reproduce the Problem**

  1. right click on blog, click enqueue selection (type is tumblr-liked-by)
  2. Click on crawl
System starts evaluating blogs, and thats all it does.
When evaluated the blogs it stops, no message, nothing dowloaded

Sometimes, but not always, a message appears " A post from 'xxxx' was not parsable. Setting posts per page to 1 in the details might increase the downloadable content.

Setting the posts per page to 1 results in the same message

This behaviour is since version 1.6.0

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
