### ISSUE TITLE
A Post from *Blog* was not parsable. setting post for page.......

### ISSUE THREAD

**Issue by jimmyfi** [TumblThreeApp/TumblThree#167]
Its been a while when I last ran TumblThree But now when I did I saw that almost every blog gave the error on the title. I checked the real website and saw that there was an extra layer of Consent to be made on the site before pictures were shown.. could it be the reason the backups don't work properly?

I tried changed the settings to 1 and cleared settings folder but it didnt help at all :(

WKR Hannu

**Comment by thomas694** [comment]
Are you using the newest version?
Have you logged in in the settings dialog and also used the second button to be able to do the consent confirmation?
Do you see an error in the log file at the time this error happens?

**Comment by jimmyfi** [comment]
> 
> 
> Are you using the newest version?
> Have you logged in in the settings dialog and also used the second button to be able to do the consent confirmation?
> Do you see an error in the log file at the time this error happens?

Yes I am using latest version.. I logged out and relogged in from settings and Now it seems to work :) Could be that it was just an died out cookie?  Consent button took me to some CAT search :D Lots of cat blogs.. :D But in summary case was easy to close :D

**Comment by thomas694** [comment]
Yes, one of the cookies expired. The page loaded in the dialog of the consent button either shows another consent warning about one second after page load or not, if that cookie is still valid.
