### ISSUE TITLE
Nothing seems to be happening?

### ISSUE THREAD

**Issue by UXlibrarian** [TumblThreeApp/TumblThree#168]
I just downloaded the latest version. I've been running this for three days but still haven't seen anything download. It says that the blogs are online and that the crawl is running. I've probably let it run for about 5-8 hours so far with nothing downloaded. I am trying to get it to download my likes which are at around 26,000 total. I'm running this on Windows 10.

**Comment by thomas694** [comment]
Hello,
you don't have to wait so long to see if it works or not. After a couple of seconds you should see if it downloads something.
Have you logged in in the settings dialog? Have you also confirmed the second cookie consent with the second button?
If that doesn't help, please describe in more details what you are seeing in the queue list and if you can find an error in the file TumblThree.log.

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.

**Comment by ViceChief** [comment]
Hey thomas694, I'm sorry to revive a dead issue but unclear about Github etiquette. I'm running into a similar issue, specifically with likes, on 2.4.1 (thank you for this recent update!). 

I've read your documentation and the issues associated with likes. I've authenticated, clicked the second button which searches for cats, and tumblthree reports being authenticated with my username. 

I've added https://www.tumblr.com/likes and my actual blog URL https://www.tumblr.com/liked/by/myblog (which I am slightly reluctant to post here in public, but if it is helpful, I can share it with you) . 

I've verified that my likes are publicly visible at that URL using private mode in a second browser.

Only the https://www.tumblr.com/likes URL seems to be able to download at all. No queue of files appears, and it takes a very, very long time for the process to start - like hours.  I don't mind this but it freezes after about half (428 of 928) items are downloaded. Oddly, I have around 2500 likes but this is not reflected in the number of downloads. 

I've opened tumblthree.log (attached) and it seems to be primarily complaining about the clipboard, but I am not really qualified to intepret what's happening. 

I'm not clear on how to continue troubleshooting, and hope I am not missing something simple here. Thanks again for your work on this app and for reading this.

![tumblthree](https://user-images.githubusercontent.com/43143928/140980508-ccbb7696-2e38-42cb-81a1-9f28e9eaf666.JPG)


[TumblThree.log](https://github.com/TumblThreeApp/TumblThree/files/7507010/TumblThree.log)

**Comment by thomas694** [comment]
created a new issue
