### ISSUE TITLE
Corrupted twitter video files

### ISSUE THREAD

**Issue by T-prog3** [TumblThreeApp/TumblThree#169]
**Describe the bug**
While testing the Twitter blog downloader i noticed that almost all video files downloaded are between 10-90kb in size and corrupted so they wont play, Some of these play half a second before terminating.

**To Reproduce**
1. Add a twitter blog that have any video content
2. Download
3. Check the download location

**Desktop (please complete the following information):**
 - TumblThree version: [2.2.0]
 - OS: Windows 10 Home

**Comment by thomas694** [comment]
Thanks for reporting a bug.

Yes, we have already seen something like that.
For sure it depends on the blogs added. But over a longer period and across multiple different blogs we had around 15k videos from which half are smaller than 100kb. Among the small files there are converted gifs and really small video dimensions which are both ok. So here only around 10% of the video files are broken.
At the moment of the download the app is downloading the whole video with size A and the download is without errors, some time later when you download the same video again it has size B for still unknown reasons. This happens for current as well as very old blog posts.
Is this also visible when viewing blogs in the browser?

There is another issue with pictures. Sometimes an image is downloaded with size A, if you download the blog 1-2 days later again, the same looking image has another size B, although the id/guid is the same. It looks like this happens mainly to "pro" blogs.

What happens there?
Maybe someone has more information about that behavior and can share it.

**Comment by thomas694** [comment]
We are sorry the first one was on our side.
Twitter optionally delivers videos either in one piece or as chunks. The chunked download wasn't handled well. In the new version the chunked downloads are handled correctly until the end too.
