### ISSUE TITLE
Request: Ability to add different collections

### ISSUE THREAD

**Issue by T-prog3** [TumblThreeApp/TumblThree#170]
**Is your feature request related to a problem? Please describe.**
1. When you have lots of blogs it becomes more difficult to organize the download folder. I know that it's possible to override the default download location on users and create your own structure as something like:

> "C:\default-download-location\Art\blog-name"

> "C:\default-download-location\Meme\blog-name"

> "C:\default-download-location\Random\blog-name"

2. But if i want to update blogs that is only related to Art then i have to manually check every blog to find and select in order to update. And every new blog i want to add to my structure i have to manually override the default download location and use my personal structure.

**Describe the solution you'd like**
1. A solution to both of these problems would be to introduce collections. This could be acting as both a **personal filter** to sort by and a default download location to that group.

2. Lets say that you start with a **default collection** and have the ability to create **personal collections** in the settings. You then have the ability to change the **Active collection** in the toolbar.

3. If a **non-default collection** is selected then every blog you add will be added to that **active collection** and get that filter name. And the blog will be downloaded to:

> "C:\default-download-location\Collection-name\blog-name"

**Comment by thomas694** [comment]
Thanks for your feature suggestion.
Sounds like a good idea and we should give it some thought.

Meanwhile I'd like to give you a hint how to have a workaround for the filtering resp. selection problem. You can use the 'personal notes' column, if you haven't used it for another purpose yet, then you could sort the list and update blogs more easily.

Of course, it doesn't solve the thing with the different download locations.

**Comment by T-prog3** [comment]
The functionality of the collections works great and made things a lot easier . Only problem i have seen so far is one that occurred during a download but nothing that broke the program:

> Exception message
> 
> Specified cast is not valid.
> 
> Exception type
> 
> System.InvalidCastException
> 
> Callstack
> 
>    at TumblThree.Presentation.Converters.CollectionMultiConverter.Convert(Object[] values, Type targetType, Object parameter, CultureInfo culture) in C:\projects\Tumblthree\src\TumblThree\TumblThree.Presentation\Converters\CollectionMultiConverter.cs:line 14
>    at System.Windows.Data.MultiBindingExpression.TransferValue()
>    at System.Windows.Data.MultiBindingExpression.Transfer()
>    at System.Windows.Data.MultiBindingExpression.UpdateTarget(Boolean includeInnerBindings)
>    at System.Windows.Data.MultiBindingExpression.AttachToContext(Boolean lastChance)
>    at System.Windows.Data.MultiBindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
>    at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
>    at MS.Internal.Data.DataBindEngine.Run(Object arg)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 
> Inner exception

**Comment by thomas694** [comment]
I wasn't able to reproduce the described problem here, even I followed your description of the steps. After around a second that is spent for downloading the blog's information my blogs were added to the list.
But I looked on your pasted error information and I think I know what the problem might have been. In the current version it is fixed. Please get back to us if you still have problems then.

**Comment by thomas694** [comment]
For a couple of reasons the index files will be moved to the collection's index folder. Also a new folder for the downloaded files will be created in the collection's root, but the old downloaded files are not moved and remain on the old location.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
