### ISSUE TITLE
I can't download files on original size.

### ISSUE THREAD

**Issue by abdulkerimbozdag** [TumblThreeApp/TumblThree#171]
Hi, I'm downloading the same file both Tumblr from both their site and TumblrThree. But the size of the file I downloaded from Tumblr's own site is larger and better. I can't download the original file with TumblrThree. I'm waiting for your help.

**Comment by thomas694** [comment]
Hello,
what is your value of "image size (px)" on blog tab in the settings dialog?

**Comment by abdulkerimbozdag** [comment]
I'm having this problem while downloading pictures from himalayev blog. I'm not using Browser, I'm using Tumblr's own client.
Blog: himalayev.tumblr.com
Compared photos:
Tumblr own client; 2.27 MB
![Tumblr_l_38972444793048](https://user-images.githubusercontent.com/16171867/137138424-5bc97c4a-6db6-425f-b57d-f8c20491206e.jpg)
TumblThree; 187.58 KB
![8ac4fdacc901574c95f937b59b304e71e45dbd22](https://user-images.githubusercontent.com/16171867/137138574-84939021-3924-40a4-b427-1df91e05f486.jpg)
