### ISSUE TITLE
limited downloads even blog has 5000 postings

### ISSUE THREAD

**Issue by bloke90** [TumblThreeApp/TumblThree#174]
Since yesterday or day before TumblThree only downloads some of the postings. Files have date-tag from last days only, before the older postings were re-tages for 1.1.1970 .... 

I suppose Tumblr has introduced a new "feature" which TumblThree need to deviate somehow?

So we all wait for next TumblThree update

example try: https://queen-kaia.tumblr.com - this blog is since 2017 and should have thousands of posts - howeve it only downloads 94....

**Comment by thomas694** [comment]
If nothing is changed it shouldn't be necessary, but you go to the folder %LOCALAPPDATA%\TumblThree\Settings (e.g. C:\Users\UserName\AppData\Local\TumblThree\Settings) and delete the Settings.json before starting the application.
...
I'm glad to hear that you solved it.

**Comment by bloke90** [comment]
ah maybe because I use my other blog account in parallel with diffrent browser?

**Comment by bloke90** [comment]
re-extracted the zip file, deleted all ... https://elie-kurtz.tumblr.com/ stops at 100 posts?

I installed Google Drive Version 51.0.16.0 recently (which is now shown like a drive) and deleted the old "backup&sync"-did thta change anyhting?
