### ISSUE TITLE
Unable to interact with Authenticate window

### ISSUE THREAD

**Issue by fruvous** [TumblThreeApp/TumblThree#175]
**Describe the bug**
Unable to interact with authenticateView window

**To Reproduce**
1. Go to Settings
2. Click on Connection tab and click Authenticate button
3. AutheneticateView appear asking for Email/Password
4. Cannot click/type/interact with this window.  Cursor stuck as pointing finger
5. Behaves as if it is waiting for something else to clear.  When I go down a window to settings, it dings but no error sound when I click in AuthenticateView

**Expected behavior**
Expect to be able to click in AuthenticateView and enter creds.

**Screenshots**

**Desktop (please complete the following information):**
 - TumblThree version: 2.4.0.204
 - OS: Windows 10 Pro N
 - Browser Default set to Edge.  Tried setting default to Chrome, same behaviour
 - Version Edge:  94.0.992.50  Chrome:  94.0.4606.81

**Additional context**

**Comment by amaitland** [comment]
If you are using an Intel 11th Gen iris graphics cards then you'll need to update your driver. 

https://www.intel.com/content/www/us/en/support/articles/000058136/graphics/graphics-for-11th-generation-intel-processors.html

**Comment by fruvous** [comment]
I don't believe I have an 11th gen GPU but updated anyways.  That did not fix the issue.

It appears that the issue is caused by the update from 1.2.0.88 directly to 2.4.0.204 might be the cause.  I started with a fresh install of 2.4.0.204 and was able to log in.  When I use the upgraded version, I can't interact with the login screen.
