### ISSUE TITLE
Setting for User-Agent does not persist

### ISSUE THREAD

**Issue by Hrxn** [TumblThreeApp/TumblThree#177]
**Describe the bug**
The custom user agent string in the settings (*Settings > Connection > User Agent*) is not saved correctly after modification.
With each new program start, the value here gets reset to some built-in default value.

**To Reproduce**
1. Change the *"User agent"* option in the *Connection* tab to some recent Chrome user-agent
2. Click save, and then close the program window
3. Start the program again
4. Observe the *"User agent"* setting in the *Connection* tab is not stored across program restarts

**Expected behavior**
My User-Agent change to `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36` should persist

**Actual behavior**
User-Agent setting in the program is `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36` again

**Desktop (please complete the following information):**
 - TumblThree version: 2.4.0.204
 - OS: Windows 10 Home 20H2 (10.0.19042)
 - Browser: Google Chrome	95.0.4638.69 (Official Build) (64-bit) (cohort: 95_Win_69)

**Comment by thomas694** [comment]
Thanks for bringing that to our attention.
A functionality was added to update the version string to the new one defined by the current version, if it follows the official pattern (so most probably untouched by the user). Of course it shouldn't "downgrade", if the string in code wasn't adjusted recently.
It will be fixed in the next version.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
