### ISSUE TITLE
File rename functionality

### ISSUE THREAD

**Issue by johanneszab** [TumblThreeApp/TumblThree#18]
*Original issue [TumblThree/#193](https://github.com/johanneszab/TumblThree/issues/193)*

Okay, since so many people keep asking this, the next thing I'll implement is a file renamer. Since I don't have that much time for the next two months, I'll lay out how I think we should do this. Thus, if anyone wants to implement something, feel free to do it:

I think we should inject it into the AbstractDownloader and rename the files right before we download them. Or we implement it into the TumblrPosts classes and add a rename method for all of the different post classes. Then all we have to do is to call post.rename().

Injecting/renaming it right before we download them and not during the crawl would have the benefit that we can compare the original found file name against the databases. Thus, all databases stay valid, and changing the rename pattern doesn't redownload the same file again.

We'll have to send the whole post or all eventually useful information down the IProducerConsumer queue, thus we'll have to modify the TumblrPosts so that it contains reblog, tag, date, title, etc. information. Everything someone might need.

Then we could add a new text box into the details view where we allow some predefined pattern for file renaming. For example something like:
```
%d-%p-%h__fixedstring
```
would create outputs like
```
20181001-title-tumblrhash__fixedstring.png
```
so that `%d` stands for the postdate, `%t` for all tags, `%h` for the tumblr hash, `%r` for reblog, `%p` for the post title, `%k` for the keyblog key. Or similar.

I'm not sure if it's possible to add a counter for all downloaded files that starts at the first post of the blog and rises, beginning with zero, but the tumblr post id is unique and rises and is mapped to each post. Thus, it will not start at zero, but at some offset and has holes, but you can eventually sort the files using the post id. It think having a counter that starts at zero is hard to do with all the async code, and if some file is inaccessible, or someone only wants to count pictures, but not videos, it's getting really messy to implement this.

If anyone has any ideas of how to do this better, feel free to comment.

**Comment by thomas694** [comment]
Information about how to use the new file rename functionality can be found in the [wiki](https://github.com/TumblThreeApp/TumblThree/wiki/File-rename-functionality).

**Comment by thomas694** [comment]
The base filename generation is done in the crawler and is passed to the downloader, so all the additional post information doesn't need to be passed on. At the time of the actual download a number may be appended to the filename to make it unique.
When using the new version old databases are updated to the new database format, but a backup of the old file is saved in the subfolder `backup`.
Formerly the downloaded files were saved in a list `Links`. Now the information is stored in a list `Entries` that contains two subentries `L` and `F` for storing the url filename and the renamed filename.
```
  "Entries": [
    {
      "F": "624028971724542032_8.jpg",
      "L": "tumblr_original_filename.jpg"
    }
  ],
```
In that way, a maybe too general filename (eg. image_123.jpg) can be referenced back to its original filename. If both are the same (using the old filename mode), the second entry is omitted in the database file to save space.

Please keep in mind that this is a new feature and may need further improvements in the future. If you are uncomfortable with it or want the old naming style, you can just use the template `%f` and TumblThree will behave like before.

Feedback and suggestions are welcome.
