### ISSUE TITLE
Latest version doesn't download entire blog.

### ISSUE THREAD

**Issue by Someonemustnothavethis** [TumblThreeApp/TumblThree#181]
I added several new blogs this month that had several hundred pages but TumbleThree only grabbed less than 100 images from each blog.  I verified that the settings where correct.   I also verified that it wasn't going back very far.

**Comment by Someonemustnothavethis** [comment]
I should also add that I deleted the blogs from TumbleThree, deleted the two files in the archives then added the blogs again with the same result.

**Comment by thomas694** [comment]
As you tried both and still it doesn't download much, it might be that they changed some structures again that can affect some or all blogs.
Have you also tried the latest version?

**Comment by xathian** [comment]
Same is happening for me. I can see quite possibly 4000+ images on the blog itself, but even with every download option enabled (reblogs, audio, video, etc) I only get 26 downloads.

Also, I noticed during the actual download process it keeps saying

"Evaluated X tumblr blog sites" 

with X being an increasing number between every image downloaded, for example

20171231_169138821538_.png downloaded
Evaluated 1 tumblr blog sites
20171231_169138821538_.png
Evaluated 2 tumblr blog sites
20171231_169138821538_.png
Evaluated 3 tumblr blog sites
20171231_169138821538_.png
etc etc

**Comment by thomas694** [comment]
Just used a fresh installation (default settings) and downloaded a blog with ~1800 images without problem.
So it looks like the problem is more related to the blogs you want to download than in general.

@xathian "Evaluated X tumblr blog sites"
Are you downloading a hidden blog? Did you try the other crawler?

@Someonemustnothavethis @xathian You can have a look in the log file, if there's an error in it. Or you email me one of your failing blogs and we'll see what keeps them from being downloaded.

**Comment by Someonemustnothavethis** [comment]
Hi Thomas,
   Here's the two blogs that are giving me trouble (please don't post
them on the Github blog, it's a bit embarrassing)

https://www.tumbex.com/blouse-and-skirt.tumblr/posts?page=1
https://www.tumbex.com/pssst-kimberlycd.tumblr/posts?page=1

  I've always used Tumbex vice Tumblr itself because the archive view
is so much faster
and well laid out.  Because I can grab stuff sooo much faster and
easier with TumbleThree, I don't even bother following
Tumblr blogs themselves except for the few that have no archive view.

  Where is the log file kept?  I couldn't find anything anywhere in
the installed directories.
Thanks for your help.
  Rob
	@Someonemustnothavethis @xathian You can have a look in the log file,
if there's an error in it. Or you email me one of your failing blogs
and we'll see what keeps them from being downloaded.

**Comment by Someonemustnothavethis** [comment]
Hi again Thomas,
   I just added another blog (
https://www.tumbex.com/vixenhotwife-dreaming.tumblr/posts?page=1 )
(Hopefully you won't think less of me because of my choice of blogs)
and watched it download.
Downloaded files - 783
Number of downloads - 846
I saw 560 images in my image browser (XnView).  It's hard to tell
where TumbleThree left off downloading
because XnView sorts alphanumerically and I don't know if/how
TumbleThree re-numbers files, or if it
does.
     Thanks again for your help and development of TT.  I'd really
love to donate if I could.
        Rob
On 11/3/2021 at 9:59 PM, "Thomas"  wrote:
	Just used a fresh installation (default settings) and downloaded a
blog with ~1800 images without problem.
 So it looks like the problem is more related to the blogs you want to
download than in general. 

	@xathian "Evaluated X tumblr blog sites"
 Are you downloading a hidden blog? Did you try the other crawler? 

	@Someonemustnothavethis @xathian You can have a look in the log file,
if there's an error in it. Or you email me one of your failing blogs
and we'll see what keeps them from being downloaded. 

	—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Someonemustnothavethis** [comment]
Oops....
I guess that blows that.  I didn't realize that emails go directly to the blog.
*sigh*

**Comment by thomas694** [comment]
@Someonemustnothavethis 
It's all good. Next time you know what notification emails are. 😉

**Comment by thomas694** [comment]
Current TT with default settings.

Blog 1:
API crawler
1327 posts, 1451 downloads
images  1321 of 1327, duplicates
texts   130 of 130

Blog 2:
decided to use/test SVC crawler
2281 posts, 3765 downloads
images  2362 of 2713, duplicates
videos  114 of 330, duplicates
texts   1171 of 1284, duplicates
+small amount links, answers...

Blog 3:
needs SVC crawler
872 downloads
images  545 of 770, duplicates
videos  1 of 6, duplicates
texts   198 of 282, duplicates
+links and answers

So the bad news is that I can't see yet what could go wrong with these blogs.

The log file should be either in "%LOCALAPPDATA%\TumblThree" or in the installation folder, depending on the used mode.
By default, TT uses the original filenames.

**Comment by Someonemustnothavethis** [comment]
Thomas,
Are these the three blogs I sent you?  If so, my installation is only seeing a small percentage of the available images.
Here's the log file.  Is it just a text file?  
Oops it won't attach or copy & paste.   I'll attach it to an email.
Rob

**Comment by Someonemustnothavethis** [comment]
Attached is a screenshot of my installed directory.  As you can
see, it's a mess.
I have no idea how to properly install updates as there's no
instructions, so I found that
sticking everything in a new subdirectory works fine (I hope?).   
   I couldn't attach the log file as it's 83 megs so here's the link
on my Mega drive....

https://mega.nz/file/c2Ij0K6C#3jFgpK795hMmfGHoKWUTBbdgQRkarGbzyYYHk-F11qw

    Thanks again,
     Rob

**Comment by thomas694** [comment]
Hi Rob,
please be aware that only an email directly and only sent to the address in the profile would be private.
I saved it and will take a look into it later.
Thomas

**Comment by thomas694** [comment]
@Someonemustnothavethis 
Here are a few notes.
- Your 1st blog seems broken. If not already done, remove it, ensure the two blog files inside the Index folder are removed, then add the blog again.
- You can delete your big log file, it will create a new one.
- Aside from that there are no clues why your mentioned blogs should not download.

How to do an update is explained in this [article](https://github.com/TumblThreeApp/TumblThree/wiki/How-to-update-the-Application%EF%BC%9F). The newer versions do these steps automatically after confirmation.
If you have a mess in your installation folder, you can remove everything in that folder and extract the zip file for the current version. (in case of "portable mode" the settings files would need to be kept)

**Comment by Someonemustnothavethis** [comment]
It worked fine this time around and deleting and reloading the problem blogs all loaded the expected number of images.  I don't know if you made a change that fixed it, or if it was something I did, but it's working fine now.   Thanks for your help and patience with me.  
I'll close this thread.
