### ISSUE TITLE
Number of (posible) Download to less at first use

### ISSUE THREAD

**Issue by ThomasFr42** [TumblThreeApp/TumblThree#183]
TumblThree Vs 2.4.1.210

If there is a new blog added to the blog-list
the number of Download is low e.g. 80 even it is a large blog with
many many entries. If I start an download it downloads only the 80.
If I copy the url of the blog and I remove the blog.
And If I do Add Blog with the copied url and there is a rescan, then the Number of Download
is much higher (e.g 20000). Then TumblThree downloads all 20000.

How I get the real hihger Download Number at the first time ?

**Comment by thomas694** [comment]
I haven't seen that behavior by default yet. In rare cases a download might stop due to an error, but then it should get all without problems on the next download attempt.
Are you downloading hidden blogs? Do you have this problem with every blog added or only some? Do you really need to remove and add them again or just try to download it again or restart the app?

**Comment by Cren0** [comment]
I´m not sure that did I understand this correctly, but just to throw in a comment (no hijack intended): I think that I have used some sort of check clipboard button; as it adds the copied tumbler sites automatically to app. So I was wondering that how the nmbr of downloads was almost every time like 120-200, even that I knew that blog was way bigger. Now thanks to this, I disabled the chck clipboard button and manually added those blogs via enter URL box and press add blog and instantly it scanned way more pictures for download (over 8000), so thank you I never thought it could be the reason why it did not detect all pictures from the blog. Thanks for this....

**Comment by thomas694** [comment]
@ThomasFr42 Do you add your new blogs manually with the url box or automatically with the clipboard monitor?

**Comment by Cren0** [comment]
I now add new blogs manually without clipb. monitor, as...I don´t know what happened...when blogs was added with clipb. monitor it only detected like 90-200 pictures....I installed app again and still no help. Now when new blogs are copy/paste manually, pictures and all is detected way more.....like over 8000...seems to work for me now anyway...

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.
