### ISSUE TITLE
Numbering and Comment Field

### ISSUE THREAD

**Issue by ThomasFr42** [TumblThreeApp/TumblThree#185]
If there would be a numbering of blog entries, there
were a advantage to see if a new blog ist inserted succesfully.

e.g.
1   blogname a         100 200
2   blogname a         400 800
...

If there could be one comment-field for the user this would be convenient.
e.g
1   blogname a         100 200       see next week
2   blogname a         400 800       bl a is better

**Comment by thomas694** [comment]
TumblThree already has a comment field ("personal notes") for blogs. You might have to make it visible by right-clicking on the header row if you don't see it.

The advantage of a numbering I don't get. Especially as newly added blogs are added to the end of the list by default. You just have to scroll the list down a bit if the end is out of view. Later you could sort the list by "Date added".

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.
