### ISSUE TITLE
Liked-by crawler not downloading all posts

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#187]
[ed.] I'm running into a[n] [...] issue, specifically with likes, on 2.4.1 (thank you for this recent update!). 

I've read your documentation and the issues associated with likes. I've authenticated, clicked the second button which searches for cats, and tumblthree reports being authenticated with my username. 

I've added https://www.tumblr.com/likes and my actual blog URL https://www.tumblr.com/liked/by/myblog (which I am slightly reluctant to post here in public, but if it is helpful, I can share it with you) . 

I've verified that my likes are publicly visible at that URL using private mode in a second browser.

Only the https://www.tumblr.com/likes URL seems to be able to download at all. No queue of files appears, and it takes a very, very long time for the process to start - like hours.  I don't mind this but it freezes after about half (428 of 928) items are downloaded. Oddly, I have around 2500 likes but this is not reflected in the number of downloads. 

I've opened tumblthree.log (attached) and it seems to be primarily complaining about the clipboard, but I am not really qualified to intepret what's happening. 

I'm not clear on how to continue troubleshooting, and hope I am not missing something simple here. Thanks again for your work on this app and for reading this.

![tumblthree](https://user-images.githubusercontent.com/43143928/140980508-ccbb7696-2e38-42cb-81a1-9f28e9eaf666.JPG)

[TumblThree.log](https://github.com/TumblThreeApp/TumblThree/files/7507010/TumblThree.log)

_Originally posted by @ViceChief in https://github.com/TumblThreeApp/TumblThree/issues/168#issuecomment-964408106_

**Comment by thomas694** [comment]
@ViceChief I made a new issue out of your comment.

The log file snippet isn't showing us too much. If you like, you can disable the clipboard monitor by clicking on the clipboard button in the toolbar, they blue highlighting should disappear.

It looks like there might be a problem with the liked-by downloading. I need to have a closer look in the next days.

**Comment by ViceChief** [comment]
Clipboard checking disabled. I'll be monitoring closely in case there is anything you'd like me to try.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.

**Comment by ViceChief** [comment]
Worked with version 2.4.2 . For what it's worth, I noticed "Downloaded files" and "number of downloads" on the UI update sporadically, and the process appears to take minutes to begin, however, once it started, all seemed well. Obviously time-to-start doesn't really matter. Thanks for the quick fix.

**Comment by ViceChief** [comment]
Also for the record, it was the /liked/by/ URL that worked.
