### ISSUE TITLE
Support for Tumblr blogs with non Tumblr urls

### ISSUE THREAD

**Issue by johanneszab** [TumblThreeApp/TumblThree#19]
*original issue [TumblThree/#325](https://github.com/johanneszab/TumblThree/issues/325)*

Currently, Tumblr blogs with a custom domain cannot be added to TumblThree. However, they can already be downloaded using TumblThree by manually extracting it's underlying *\*.tumblr.com* domain from the websites source code as [demonstrated in this post](https://github.com/johanneszab/TumblThree/issues/21#issuecomment-282686781).

**Comment by johanneszab** [comment]
@gpriaulx already has an implementation idea as seen in [this post](https://github.com/johanneszab/TumblThree/issues/325#issuecomment-459317001).

**Comment by thomas694** [comment]
The issue has been fixed (#101) and closed.
