### ISSUE TITLE
it downloads nothing for liked/by blogs

### ISSUE THREAD

**Issue by wacher74** [TumblThreeApp/TumblThree#196]
**Describe the bug**

I upgraded to lastest version today (2.4.5.231).
I have one blog url, it has been downloaded regularly until today.

Now: Evaluated 1088 tumblr blog sites. 
But it downloads nothing.

Dowgrade to TumblThree-v2.4.3-x64-Application
It is working again.

Other issue: since I use W11, filedate of every downloaded image file is 1970.01.01

**Desktop (please complete the following information):**
 - TumblThree version: 2.4.5.231
 - OS: Windows 11 Pro
 - Browser Edge Chrome 
 - Version 96.0.1054.53

**Comment by thomas694** [comment]
So all your blogs work except one which doesn't download?
Can you try if version 2.4.4 works for you?

We don't have Win11 here yet, but we'll keep an eye on it.
Does anyone else have Win11 and experience the date problem?

**Comment by wacher74** [comment]
I have only one URL (liked/by).
2.4.4 works well.
Downloaded mp4 files have good timestamps.
Downloaded image files (jpg,png,gifv) have bad timestamps.

**Comment by dajotim937** [comment]
Hi, I have similar problem.
blog: multiboot2.tumblr.com
After I added blog and select to download everything it doesn't download first post with 2 gifs. Maybe something else also but there is a lot posts and didn't check everything.
Also I get wrong name with video in different post it has default name.
Reblogged both posts so you can find which ones are wrong: https://www.tumblr.com/blog/dajotim937

**Comment by jjdnl** [comment]
Hi same issue here.
2.4.5.231 not downloading anythiing, just evaluating.
Previous version does download.

**Comment by thomas694** [comment]
@dajotim937 
I created a new issue for that one.

@jjdnl 
What blog type are you trying to download?

**Comment by jjdnl** [comment]
@thomas694 It's a liked by type of blog

**Comment by thomas694** [comment]
@wacher74 @jjdnl 
If you like, you can test whether the [upcoming version](https://ci.appveyor.com/api/buildjobs/iug5t2l7wq41n59p/artifacts/artifacts%2FTumblThree-v2.4.5-x64-Application.zip) works for you.

**Comment by wacher74** [comment]
It is working for me, thank you :)
Files are downloaded, and their timestamps are correct.

**Comment by jjdnl** [comment]
Yes, working for me too. Thanks

**Comment by bloke90** [comment]
I use the latest version (updated by auto-updater) but it doesn't download... will try to overwrite it with files from zip file

**Comment by dajotim937** [comment]
> I use the latest version (updated by auto-updater) but it doesn't download... will try to overwrite it with files from zip file

Auto-updater doesn't download because there is nothing download. Actual [public release](https://github.com/TumblThreeApp/TumblThree/releases) with fix isn't made yet.

**Comment by thomas694** [comment]
Correct. The given link is a version for testing purposes.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
