### ISSUE TITLE
Consolidate and import existing issues.

### ISSUE THREAD

**Issue by elipriaulx** [TumblThreeApp/TumblThree#2]
The legacy repository issue list should be reviewed, consolidated and migrated here, to capture the current state of functionality.

https://github.com/johanneszab/TumblThree/issues

It might be worth closing the issue at the original source and noting the relocation.

**Comment by johanneszab** [comment]
I'll do this as once we're agreed on a (new) name. I'll set my personal johannes/TumblThree repository as "archived" and add redirect notes to the release and issue pages, as well as update the README.md. I hope that should cover most users.

**Comment by johanneszab** [comment]
As for the issues, maybe once we start working on them, we can simply re-open it here? Over the next weekend, I'll also manually import some of them and add some notes about it of where to find stuff/how I'd look for it as it might simplify the "get into it" for you/new contributors.

Maybe we should add tags for prioritizing the issues? We should also add a CONTRIBUTING.md right away on how to properly open a new issue (i.e. post more than one sentence).

**Comment by gpriaulx** [comment]
Cool, lets make a move on this. Tags sound like a great idea. We should leverage the 'Help Wanted' tag and others, to leverage promotional tools to gain contributors like http://github-help-wanted.com/
The notes and insight would be of great help here.

Are you alright taking over this issue @johanneszab ? If there is any leg work I can do to help, delegate! 👍

**Comment by gpriaulx** [comment]
Cool, lets make a move on this. Tags sound like a great idea. We should leverage the 'Help Wanted' tag and others, to leverage promotional tools to gain contributors like http://github-help-wanted.com/
The notes and insight would be of great help here.

Are you alright taking over this issue @johanneszab ? If there is any leg work I can do to help, delegate! 👍
