### ISSUE TITLE
Support for personal tumblr likes

### ISSUE THREAD

**Issue by johanneszab** [TumblThreeApp/TumblThree#20]
*Original issue [TumblThree/#337](https://github.com/johanneszab/TumblThree/issues/337)*

TumblThree should be able to download personal tumblr likes via the https://www.tumblr.com/likes url. Currently, it can only download likes using the publicly visible likes page at [https://www.tumblr.com/liked/by/*blogname*](https://www.tumblr.com/liked/by/blogname). The capabilities of this page however were changed at the 17th December 2018. Thus, enabling the personal likes page would result in more downloadable content.

The costs for this feature should be minimal as it probably only requires to change the UrlValidator (might relate #19) allowing it to add the personal likes page and possibly the "likes-url" builder within the TumblrLikedByCrawler.cs.

**Comment by htttd35** [comment]
> *Original issue [TumblThree/#337](https://github.com/johanneszab/TumblThree/issues/337)*
> 
> 
> 
> TumblThree should be able to download personal tumblr likes via the https://www.tumblr.com/likes url. Currently, it can only download likes using the publicly visible likes page at [https://www.tumblr.com/liked/by/*blogname*](https://www.tumblr.com/liked/by/blogname). The capabilities of this page however were changed at the 17th December 2018. Thus, enabling the personal likes page would result in more downloadable content.
> 
> 
> 
> The costs for this feature should be minimal as it probably only requires to change the UrlValidator (might relate #19) allowing it to add the personal likes page and possibly the "likes-url" builder within the TumblrLikedByCrawler.cs.

**Comment by thomas694** [comment]
@arrowsmith001 
Thanks for working on that one.
