### ISSUE TITLE
Login Name now n/a

### ISSUE THREAD

**Issue by harryh892** [TumblThreeApp/TumblThree#201]
On the setting page, I login with my credentials, see in the mini browser my homepage, but the setting page says logged as n/a.  This started a revision or so ago and I'm now on 2.4.6.235.  It has always worked before.

**To Reproduce**
1. Go to 'settings'
2. Click on 'connection'
3. Scroll down to 'authenticate.  Complete the form, see my homepage'
4. Login says Logged in as n/a

**Expected behavior**
Should show my screen name, as in the past

**Desktop (please complete the following information):**
 - TumblThree version: [e.g. 2.4.6.235]
 - OS: Win 10 Pro
 - Browser Vivaldi
 - Version 5.0.2497.32 

**Additional context**

**Comment by thomas694** [comment]
Thanks for reporting an error.
It has already come to our attention and we have done a second fix (#192) that will be in the next version.

Before it said that the user is still logged out even the login was successful. We had done a fix a few days ago, unfortunately Tumblr already changed their data structures again. But at least it says now "Logged in" even if the account name cannot be read and shown which should confuse the user less than before.

**Comment by harryh892** [comment]
Thanks for clearing this up.  Shooting a moving target is hard, appreciate the effort.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
