### ISSUE TITLE
Wrong app language

### ISSUE THREAD

**Issue by dajotim937** [TumblThreeApp/TumblThree#202]
Last version build, in settings set English, all settings in english but main window is russian.
<details>
  <summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/96221151/148546091-f7357bf8-9443-480e-ab91-1bea1079a983.png)
![image](https://user-images.githubusercontent.com/96221151/148546094-6278b927-72e0-4168-8a9a-a6a17c6f6ba8.png)

</details>

**Comment by thomas694** [comment]
Thanks for reporting that one.
Yes, something is broken with the main window translation.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
