### ISSUE TITLE
Downloaded file is huge compared to actual image data.

### ISSUE THREAD

**Issue by Caedmon716** [TumblThreeApp/TumblThree#207]
Here are two images downloaded, one via search and the other via tag.

11/05/2021  05:19 AM    13,566,391,920 51127871052_d34bbf21a4_b.jpg
12/08/2021  10:52 AM     8,101,249,935 51127871052_d34bbf21a4_b^Harley+Quinn.jpg

The two images by image data in a viewer are 1.69 MB each and identical though on disk one is 12.6 GB and the other is 7.54 GB.

51127871052_d34bbf21a4_b.jpg

1024 x 576  Pixels (16:9)
16,7 Million   (24 BitsPerPixel)
12937.92 MB (13,566,391,920 Bytes)
1.69  MB (1,769,512 Bytes)

51127871052_d34bbf21a4_b^Harley+Quinn.jpg

1024 x 576  Pixels (16:9)
16,7 Million   (24 BitsPerPixel)
7725.95 MB (8,101,249,935 Bytes)
1.69  MB (1,769,512 Bytes)

I went searching for more as missing disk space was what started my search.  I found 39 files, all JPG and all downloaded via search or tag that totaled 111 GB. The oldest was 11/04/2021 and the newest was on 01/05/2022.

I am using v2.4.8.243 and have upgraded at each version within a few days of release.
OS: Windows 10 Home

I will be on the lookout for new images to update.

**Comment by thomas694** [comment]
Thanks for reporting a bug. We'll take a look at it.

**Comment by Caedmon716** [comment]
I removed the tag search and added a few times just for kicks. These three posts among others cause TumblThree to do whatever it does every time it tries to download them.

https://airmanisr.tumblr.com/post/673749867606228992/queen-of-belle-reve-by-pat-loika-via-flickr
https://airmanisr.tumblr.com/post/673703683143483392/harley-quinn-59-foil-signed-by-derrick-chew-by
https://airmanisr.tumblr.com/post/673735649295237120/r5119951-winterfest-2021-momocon-sat-12-18-21-by

When I look at
https://airmanisr.tumblr.com/archive
these posts show up as a video link though they are JPGs hosted on flickr.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
