### ISSUE TITLE
Limit exceeded.

### ISSUE THREAD

**Issue by VRArt1** [TumblThreeApp/TumblThree#209]
**Expected Behaviour**

Crawl blogs.

**Actual Behaviour**

Received Limit Exceeded error. Suggested to lower Tumblr api number of connections. No change when lowered.

**Steps to Reproduce the Problem**

Detail the steps below to help us reproduce the problem you encountered.

  1. Add twitter blog to Queue.
  2. Click Crawl.

**Specifications**

Windows 10 Home. TumblThree 2.4.8.243

**Comment by VRArt1** [comment]
Update. I tried crawling only tumblr blogs and those were able to crawl. This error seems to only be affecting Twitter "blogs".

**Comment by thomas694** [comment]
Thanks for reporting a problem.
Yes, a few days ago the Twitter crawler stopped to work. It is still unclear why. Looking on the error message it seems to be a problem on their side, and it wouldn't be the first time. But even if the error message should be another one then, it could be a problem in the app, if maybe they changed something in the structure or identifiers.

Does anyone have more information?

**Comment by Hrxn** [comment]
Yes, I know why.

A couple of days this "NFT avatar image" change went live, and there has been changes to their site backend in the same vein, like apparently turning off the old API.

Only the new GraphQL API remaining, it seems...
https://blog.twitter.com/engineering/en_us/topics/infrastructure/2020/rebuild_twitter_public_api_2020
https://gist.github.com/MichaelCurrin/ae75545c451629b909a7dd7580a08add

**Comment by thomas694** [comment]
Thanks. Yes, I already found the first link. The second one is an example, also back from 2020. Do you have another link what they discontinued a few days ago?
But that doesn't explain why the urls are still accessible, some work normally and some return 429 instead of 404 or any other error code.
I have to look further in the next days.

**Comment by Hrxn** [comment]
I'd simply assume that the inconsistent return results and error codes stem from a gradual roll-out of the backend changes, that's all

**Comment by thomas694** [comment]
It should work again now.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
