### ISSUE TITLE
Add proper logging functionality

### ISSUE THREAD

**Issue by johanneszab** [TumblThreeApp/TumblThree#21]
Original issue [TumblThree/128](https://github.com/johanneszab/TumblThree/issues/128).

Maybe use log4net or System.Diagnostics/Trace?

**Comment by gpriaulx** [comment]
My preference would be:

NLog > Log4Net > System.Diagnostics. 

Regardless, we should add an interface for this so we can start logging stuff immediately.

**Comment by thomas694** [comment]
Until a logging functionality is included, a log file can be generated by adding these lines to the file TumblThree.exe.config:
```xml
  </applicationSettings>
  <system.diagnostics>
    <trace autoflush="true" indentsize="4">
      <listeners>
        <add name="myListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="TumblThree.log" />
      </listeners>
    </trace>
  </system.diagnostics>
  <system.net>
```
The path can be configured too, if a location outside the program folder is desired (eg. initializeData="C:\Temp\TumblThree.log").

**Comment by thomas694** [comment]
Starting from version 1.0.11.11 this manual step is no longer necessary. Just choose the desired log level in the settings.
The log file will be written to %LOCALAPPDATA%\TumblThree or the current folder (portable mode).
