### ISSUE TITLE
TumblThree-v2.5.2-x64-Application seems to have problem

### ISSUE THREAD

**Issue by bloke90** [TumblThreeApp/TumblThree#215]
I made autoupdate from TumblThree-v2.5.1-x64-Application - afterwards most blogs didn't donwload anymore (hidden or unhidden, logged in or not)

I deleted whole directory plus settings (under user) - extracted TumblThree-v2.5.2-x64-Application from zip - same issues.
Deleted again and extracted the old TumblThree-v2.5.1-x64-Application - works again.

**Comment by thomas694** [comment]
Yes, it has already been brought to our attention. The download of Tumblr blogs isn't working. We'll fix it.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
