### ISSUE TITLE
"not starting no anyfiles downloaded for 20 minutes!"

### ISSUE THREAD

**Issue by hakanelver** [TumblThreeApp/TumblThree#224]
i downloaded your tumblthree 2.5.5 latest version for 32 bit as 086x.. and its execuable file in the files as exe. i clicked and open the program interface. i add a blog which one i want to download all text and images to my laptop. 
waiting and wiating and wiaiting  minutes an minutes passed but notting downloaded. even 1 kb txt file..
how its starting= where s the start button? tere is stop button so its start automatically but  why dosent work? whats wrong?
must i have to be bill gates or coder as you? user friendly? is it in your dictinory? 
what i have to domore to start and get  blog files  as you promised to people?
its locked now  cant close program from  red x at top corner. i wnated to send feedback but its  locked itself.. i cant close the program  so i trying to ctrl+alt+del now..
I am in disappointment and tired..
please is there somebody know how this program using or if this tumblrthree fake then is any way to download a blog site diffrent and easy ways please tell me. my email adress is [redacted]

**Comment by thomas694** [comment]
The way you are writing here and in your other feedback message is extremely impolite as to put it politely.
Although this doesn't deserve an answer. It helps if you can read:
> To start the download process, click on 'Crawl'.

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.
