### ISSUE TITLE
POLL: Old / New Crawl button?

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#228]
_We want your opinion and have started a small poll:_
**How do you want the Crawl button to look like in one of the upcoming versions?**

Please vote by pressing the thumbs up ![](https://user-images.githubusercontent.com/71355143/160021507-ede6b302-ed10-42a7-a7e3-5b73d0126cf5.png) under one of the options.

Thanks for your participation!

**Comment by thomas694** [comment]
keep it
![crawl_current](https://user-images.githubusercontent.com/71355143/160021733-3f290f01-174d-4c48-8d90-46dc11cd2193.png)

**Comment by thomas694** [comment]
change 1
![crawl_option_1](https://user-images.githubusercontent.com/71355143/160021743-c73bc206-ea26-444f-b1d7-fe5770580e85.png)

**Comment by thomas694** [comment]
change 2
![crawl_option_2](https://user-images.githubusercontent.com/71355143/160021753-5e850aa5-2325-4eae-a94e-18d10a2b7835.png)

**Comment by thomas694** [comment]
change 3
![crawl_option_3](https://user-images.githubusercontent.com/71355143/160021761-36820966-9cd6-4af2-b14e-1699ca53d9db.png)

**Comment by bloke90** [comment]
download is better wording

**Comment by thomas694** [comment]
Thanks to all who participated.
We'll change it to version "change 2".
