### ISSUE TITLE
Option to hide toolbar button captions

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#237]
**Is your feature request related to a problem? Please describe.**
As an user who uses TumblThree in another language than english, it's sometimes disturbing that the toolbar button widths are very different due to longer translations in other languages.

**Describe the solution you'd like**
There should be an option in the settings to hide the toolbar button captions. If this setting is enabled, only the icons would be shown on the buttons and thus the buttons are all equal width.
Maybe instead of showing no help at all, the caption texts can be shown as a tooltip.

**Describe alternatives you've considered**
To leave it as it is.

**Additional context**
![new_issue_1](https://user-images.githubusercontent.com/71355143/164943664-d42658e1-1e4e-4a18-9233-3515bae38799.png)
![new_issue_2](https://user-images.githubusercontent.com/71355143/164943666-a218f4cd-e6e9-439b-a7f4-7f3458fea646.png)

**Comment by thomas694** [comment]
[As before](https://github.com/TumblThreeApp/TumblThree/issues/101) this one is for first-timers-only. That means that we will only accept a PR for this one from someone who's never contributed to open source before. This one is particularly easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). We walk you through it if you need help. :-) Here are the steps to get a PR merged (see also our [guide](https://github.com/TumblThreeApp/TumblThree/blob/master/Contributing.md)).

There should be an option in the settings to hide the toolbar buttons' caption. If this setting is enabled, only the icons are shown on the buttons and thus the buttons are all equal width.
Additionally, if the option is enabled, a tooltip shall be shown on the buttons. The button captions can be used as texts for the tooltips.

- [x] Create a fork of the repository
- [x] Clone it to your local disk and create a new branch (e.g. 000-hide-toolbar-button-captions)
- [x] Look which class and view is dealing with the toolbar buttons. How can a tooltip be shown on the buttons? What needs to be changed?
- [x] Add your solution
- [x] Build the app and run it
- [x] Check the toolbar in the default/english language. Does it work as expected? Is a tooltip shown for all the buttons on hovering?
- [x] Switch the languages in the settings, restart the app and check again.
- [x] Commit your changes mentioning "`issue #000`" somewhere in your commit message title or description
- [x] Push your changes to your fork, create a PR, get merged, celebrate??

We are happy to support you if you need help.

**Comment by rexius41** [comment]
Hi could I take on this issue if possible

**Comment by thomas694** [comment]
Hello,
thanks for your interest. Yes, you can work on that issue.
If you have a question or get stuck, feel free to ask.

**Comment by thomas694** [comment]
Thank you for your first contribution and PR to our TumblThree project.
Your PR has been merged and you've been added to our list of contributors.
We would be happy to receive more contributions from you in the future. Maybe you can help us with one or the other issue.
