### ISSUE TITLE
Option to do not download blog's thumbnails

### ISSUE THREAD

**Issue by veneamin** [TumblThreeApp/TumblThree#239]
It would be nice to have an option "don't download blog's thumbnails"
Now i have to check  size of images and delete all 64x64 pix by running script after every download update
Or may be "minimal size to dowload" - it will solve the problem too.

**Comment by thomas694** [comment]
Please provide us more details.
Are you downloading tumblr or twitter blogs? Do you additionally use the option "search for image patterns"?
Can you provide an example filename to show the pattern they are built?

**Comment by veneamin** [comment]
>Are you downloading tumblr or twitter blogs?  

Tumbler

>Do you additionally use the option "search for image patterns"?

No. Only images and videos, see sreenshot

>Can you provide an example filename to show the pattern they are built?

The names are always  the same length and looks like  8105d2b1f9c1e7f080cdb62ad13ee729d8d281c2.jpg
File size is about 2-3 kb and 64x64 pix

![2022-04-27_23-59-50](https://user-images.githubusercontent.com/40829917/165631122-9c14baf8-191d-4a06-8285-58702d588726.png)

**Comment by thomas694** [comment]
Since Tumblr's url format change quite a while ago, no one has recognized resp. complained that the Liked/By crawler downloaded avatar images. The download of these images is suppressed now.

You can check it in the next version.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
