### ISSUE TITLE
Can't download tumblrs with content warning

### ISSUE THREAD

**Issue by evildisko** [TumblThreeApp/TumblThree#245]
I apologize in advance, I'm not technologically literate. 

The tumblr in question is http://garyglamour-thethird.tumblr.com 

It says the blog is offline. I'm authenticated in the app. 

Thanks for your help!

**Comment by thomas694** [comment]
Hello,
you are using the latest version, right? Have you used older versions before?
I just unzipped the current version, added the blog, logged in and it downloaded without problems. So either it's a (temporary) regional problem which should go away after a few days, or it's a problem with your TumblThree installation.
Did you log in and scroll half page to check if you have to confirm cookies? Did you also use the second button "privacy consent" to check if you have to accept additional cookies? I assume that there was no error message shown. You can have a look in our log file (%LOCALAPPDATA%\TumblThree\TumblThree.log, e.g. C:\Users\YourUsername\...) if there is an error at the end of the file after you have tried to download the blog.

**Comment by evildisko** [comment]
Thank you! Downloading the newest version did it for me. Have a good one!

**Comment by thomas694** [comment]
Good that it works for you again. Yes, you should always use the newest version. You too!
