### ISSUE TITLE
Survey: Shall we launch a new Forum?

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#260]
What do you think about this section "Issues" here?
Is it the right place for all kinds of "articles" like they are at the moment?
Is it too mixed up and difficult to find information? Would categories make it better?
... ?
Do you think a different representation and functionality like in "Discussion"* would benefit?

*So that you know what we are talking about, if you haven't seen it yet somewhere, here are some examples:
https://github.com/reactwg/react-18/discussions
https://github.com/nasa/cFS/discussions
https://github.com/vercel/next.js/discussions
https://github.com/AcademySoftwareFoundation/OpenTimelineIO/discussions

We would like to hear from people who are new here as well as long-term users.

Write your thoughts and opinions as comments below.

**Comment by Someonemustnothavethis** [comment]
This is a great idea!

**Comment by Hrxn** [comment]
In favor of this idea as well..

**Comment by thomas694** [comment]
The new Discussions section has been opened.
