### ISSUE TITLE
Won't 'see' some adult blogs

### ISSUE THREAD

**Issue by Someonemustnothavethis** [TumblThreeApp/TumblThree#263]
Tumblethree doesn't see some blogs.  Some can only be read in a browser by following them.  The URL for one is as follows...
(actual blog name is replaced with 'ADULTBLOG')

https://www.tumblr.com/blog/view/ADULTBLOGG?redirect_to=%2Fblog%2Fview%2FADULTBLOG&source=content_warning_wall

I tried many different combinations but TumbleThree wouldn't recognize the blog.  Is this known or is there a workaround?  And yes, I'm properly logged in.
Thanks!

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.
