### ISSUE TITLE
Job Offer $$$

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#266]
Come and support the TumblThree project.
You don't need a bachelor, master or PhD to work in our team. English language skills are sufficient.

What you will be working on:
- Reading the existing open and closed issues
- Categorizing them and moving some to the new Discussions section
- Moving issues with questions & answers, or ideas
- Leaving discussions about code or implemented features
- No text editing or rephrasing necessary, mostly selecting and clicking
- Marking unclear issues with a new label for later review
- You'll need a couple of hours going through all existing issues

Benefits:
- Work remotely
- Free time management
- The chance to contribute something good to the TumblThree project

Compensation:
- No money, but lots of gratitude
- An entry in our contributors list
- The good feeling of having contributed something to the TumblThree project

This work is limited. Further employment with other duties is possible.

Are you interested? Leave us a short comment.
<sup> </sup>
<sup> </sup>
<p align="center"><i>
“There are three kinds of people: Those who make things happen, <br>
those who watch things happen, and those who ask, ‘what happened?’” <br>
— Casey Stengel</i></p>
<sup> </sup>

**Comment by Mannuel25** [comment]
Hello @thomas694 , I'd love to take this up.

**Comment by thomas694** [comment]
Hello Emmanuel,

thanks for your support.

Although I believe you have understood the task and know how to organize yourself, I would like to give you some input. And feel free to ask any questions you have.

I have enabled the new discussions section, added you to the repository and given you the required permission to convert the issues.

All [issues](https://github.com/TumblThreeApp/TumblThree/issues), currently 267 ones, need to be revised. If an issue, e.g. #248, qualifies for one of the 3 categories "General", "Ideas" (or feature requests) or "Q&A", it can be converted to a discussion entry by clicking on "Convert to discussion", choosing the appropriate category (here Q&A) and confirming the conversion.

**Comment by Mannuel25** [comment]
Okay,thanks for the clarifications. If I have any questions. I'll do well to reach out to you. Let's get to work :rocket:

**Comment by Mannuel25** [comment]
`All issues, currently 267 ones,`. I don't understand this..do you mean there are 267 issues?

Also, I've moved a few open issues to discussions, based on their categories..that's what I'm expected to do right?

**Comment by thomas694** [comment]
There should be up to 267 issue entries, either still open or closed, maybe one or two really aren't accessible any more.

Yes, please go also through the closed issues. If they contain information or answers to a question which a user had, they might be helpful to others in the future too.

**Comment by Mannuel25** [comment]
Okay, thanks

**Comment by thomas694** [comment]
Thanks a lot @Mannuel25 for helping us.
The new discussions section got enabled and with the converted issues it doesn't look empty any more.

**Comment by Mannuel25** [comment]
> Thanks a lot @Mannuel25 for helping us. The new discussions section got enabled and with the converted issues it doesn't look empty any more.

Thanks for granting me the opportunity as well.
