### ISSUE TITLE
Some blogs don't/won't load?  

### ISSUE THREAD

**Issue by Someonemustnothavethis** [TumblThreeApp/TumblThree#267]
I've been exploring this for a while and have two good examples.
https://kirstysdreamcloset.tumblr.com/  This is a perfectly innocuous blog full of nice clothes.  I use T3 (TumbleThree) every month to catch up with the posts.  It also shows up in Tumbex's archive view,
https://www.tumbex.com/kirstysdreamcloset.tumblr/posts

Here is another perfectly innocent blog that DOESN'T load into T3,
https://www.tumblr.com/blog/view/sexysilkysatin
Notice that while I'm following it, just like the first blog example, the URL shows 'view'.  I can't make it show up the same as the other blogs I follow.
Further, this second blog also doesn't show up in Tumbex.  It shows up if I search for it,
https://www.tumbex.com/search?q=sexysilkysatin
But Tumbex can't read it's archive view,
https://www.tumbex.com/sexysilkysatin.tumblr/posts

I've noticed that this happens mostly with _some_ adult blogs but it's almost random.  The blog I've mentioned as NOT an adult one and Tumblr doesn't make me click through all the warnings it usually does for those kinda blogs.  I'm guessing that this is some random thing that Tumblrs doing.  Has anyone else noticed this or is it just me?
Yes, T3 is logged in, and I follow both blogs.

Is there a work around for this?
Thanks a bunch

**Comment by thomas694** [comment]
Normally, I add blogs by using "xyz.tumblr.com", especially blogs that are redirected in the browser.

Both blogs can be added and downloaded without a problem here. The first one is a normal and the second one is a hidden blog (login required). So at least the second one needs crawler type SVC (normally chosen automatically when added).

You can edit the files kirstysdreamcloset.tumblr resp. sexysilkysatin.tmblrpriv and check/edit (be sure your editor handles them correctly or make a backup before) the line with the URL:
  "Url": "https:\/\/kirstysdreamcloset.tumblr.com\/",
  "Url": "https:\/\/sexysilkysatin.tumblr.com\/",
if they contain any other style/pattern.
