### ISSUE TITLE
Enhance code base to allow new website crawler

### ISSUE THREAD

**Issue by johanneszab** [TumblThreeApp/TumblThree#27]
Currently there is quite an effort necessary to support a new website in TumblThree (for example reddit or instagram).

Roughly, the following steps have to be done:

* Implement the ICrawler interface and override the Crawl method to start the crawler and a DownloadBlogAsync task from the IDownloader interface. Here, most of the code should be equivalent.
* The url validator needs adjustments to detect proper urls.
* Add a BlogType.
* Add a Crawler to the CrawlerFactory.
* Add a BlogType to the BlogFactory.
* You might have to to add a new DetailsView.cs if you want different checkboxes or statistics.

It might be worth streamlining these tasks. At least for a simple RegEx grepper there should only be a few lines of code necessary (i.e. the url, the name of the new downloader/crawler and the RegEx).

**Comment by thomas694** [comment]
It should be quite straight forward to add new sites like 500px, instagram, or twitter. The downloader and most of the UI should be able to take different websites.

You can check [this commit](https://github.com/TumblThreeApp/TumblThree/commit/d1823548493b37baded60db35492f9f3040ecfe5) for the addition of the Twitter downloader as the most recent example. This commit also contains code refactorings to make the naming of the classes and methods more general.
