### ISSUE TITLE
No .EXE

### ISSUE THREAD

**Issue by owlicious** [TumblThreeApp/TumblThree#35]
My apologies if this is a humiliating newb question, but having downloaded the zip, I can't find any EXE. Should the folder within the zip called "TumblThree-master" somehow be converted to an EXE file? Thanks in advance.

**Comment by Hrxn** [comment]
Nope, looks like you are completely right.
I assume you used the green *"Clone or download"* button on the repository, main page, i.e. here: 
https://github.com/TumblThreeApp/TumblThree

This gives you a zipped archive file of the base tree of the repository, that is, only the source code, and you are right there is no executable file there, as expected.

Releases can be found on the *Releases* tab. This is also linked from the `README.MD` (which always gets displayed on ever GitHub repository page below the file listing etc.), so the link is there as expected, pointing here:
https://github.com/TumblThreeApp/TumblThree/releases

But you're right, someone forgot to make any releases so far :)

**Comment by panhartstuff** [comment]
@Hrxn What happened to the releases page? It's completely empty. Am I missing something here?

**Comment by gpriaulx** [comment]
This is probably my fault. I will sort it out in an hour or two. 

I've been procrastinating and delaying making changes - I guess I don't feel right approving my own PRs on essentially someone else's code base without more discussion around expectations first. I don't want to be stepping on toes or unwinding engineering built for something I haven't understood or been made aware of. It's probably irrational. 

I'll get back into the update groove this weekend and hopefully @johanneszab will yell at me if I do something too terrible 😅 


If you can't wait an hour or so longer - you can always get the latest build from the CI pipeline linked with the badge in the ReadMe (Appveyor). I haven't tested anything personally to have any perspective on the current head stability but I don't expect anything catastrophic. You might need .net 4.7.2 for the latest version however. 

[https://ci.appveyor.com/project/gpriaulx/tumblthree/branch/master/artifacts](https://ci.appveyor.com/project/gpriaulx/tumblthree/branch/master/artifacts)

**Comment by gpriaulx** [comment]
I have pulled in the latest 3 versions from the original repository, and created a new release at the current head. All seems to be working for me at the moment, but some feedback would be great.

Sorry again for the confusion.

**Comment by owlicious** [comment]
Thanks, ya'all (esp. gpriaulx). I was re-installing the JDK & all trying to figure out how to compile it from the source. >_< Glad there's an executable now! Will let you know if I observe any bugs.
