### ISSUE TITLE
Support https://www.tumblr.com/username format

### ISSUE THREAD

**Issue by ObfuscationJones** [TumblThreeApp/TumblThree#380]
Tumblr is starting to use `tumblr.com/username` for blogs, in addition to `username.tumblr.com`, and some blogs (flagged ones, I guess?) are now only displaying the former when you're viewing the blog. 

Since I'm usually adding a blog by copy-pasting the address from Tumblr to TumblThree, it would be convenient if we could add blogs with their `tumblr.com/username`, which doesn't seem to supported so far. If it's causing an issue with the inner working of TumblThree, it could even just be a conversion: when we press "Add blog", it's converted back into username.tumblr.com.

**Comment by thomas694** [comment]
Yes, we already saw that Tumblr changed a few things recently. We'll change it, so that TumblThree is able to recognize the new format, although internally and for displaying we probably will still use the former format.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
