### ISSUE TITLE
It keeps logging out from tumblr acc

### ISSUE THREAD

**Issue by pakiec22** [TumblThreeApp/TumblThree#407]
I am always logged out from tumblr.
When I click authenticate it opens a window and I literally have to do nothing, only close (cuz I am logged in in a opened window) it and I am logged in.
And I am logged in.
Then starting to crawl all blogs and after about 30-60mins I am again logged out and crawling is going bad when it happens.
And again and again... always the same.

I never had a problem with it, but I started crawling something again 2-3 days ago and I saw this hapenning, weeks before and more I never had such a problem.

It just keeps logging out although when clicking authenticate in window I appear as Logged in.

**Comment by thomas694** [comment]
This is also discussed in #396. We haven't found the cause of the problem yet.

Please delete your Cookies.json (in %LOCALAPPDATA%\TumblThree\Settings) while TumblThree is closed and try it again.
And are you only downloading hidden blogs or different blog types (which ones) when this error happens?

**Comment by Devloger** [comment]
I downlaod hidden and not hidden, many many of them and all kinds of them.
I did delete this cookies.json.
Still the same.

**Comment by pakiec22** [comment]
I downlaod hidden and not hidden, many many of them and all kinds of them.
I did delete this cookies.json.
Still the same.
