### ISSUE TITLE
not an issue but a small question: what about twitter?

### ISSUE THREAD

**Issue by agu4004** [TumblThreeApp/TumblThree#41]
so I was using Tumblthree quite a while, and then I have a question: what about twitter?
I would like to hear your idea about it.

**Comment by gpriaulx** [comment]
I agree entirely. While the current architecture does have provisions for this sort of thing, I feel that to keep things maintainable going forward we need a bit of a radical restructure. I'm not across every aspect of the code base yet to preempt side effects, but am getting there slowly.

Maybe we should compile a list of other sites that should be supported for when the time comes? Maybe we can abstract out a general 'agent' and testing toolkit that is easy to extend for multiple site support, and then adapt over to it?

**Comment by il-hubspot** [comment]
> 
> 
> so I was using Tumblthree quite a while, and then I have a question: what about twitter?
> I would like to hear your idea about it.

Definitively, current tools like Bulk Image Downloader are VERY unreliable.

**Comment by Tamalero** [comment]
Definitively, current tools like Bulk Image Downloader are VERY unreliable.

**Comment by fabiotnt** [comment]
I use the Twitter Media Downloader here and works like a charm.
It's a Google Chrome extension

https://chrome.google.com/webstore/detail/twitter-media-downloader/cblpjenafgeohmnjknfhpdbdljfkndig

**Comment by Tamalero** [comment]
> I use the Twitter Media Downloader here and works like a charm.
> It's a Google Chrome extension
> 
> https://chrome.google.com/webstore/detail/twitter-media-downloader/cblpjenafgeohmnjknfhpdbdljfkndig

Thank you!
I still wonder, does this tool depend on a remote site?
