### ISSUE TITLE
Crawler Sometimes Doesn't Get Full Resolution Images although it is possible

### ISSUE THREAD

**Issue by pakiec22** [TumblThreeApp/TumblThree#417]
Related to issue
https://github.com/TumblThreeApp/TumblThree/issues/66

I think it is still present, e.g. https://www.tumblr.com/betaboiseat4feet-blog
has this post
https://www.tumblr.com/betaboiseat4feet-blog/666787421031170048

And the pic can be downloaded 2-3 bigger by web.
either SVC or Api.
I can't achieve that using tumblrthree app.
The same, bigger size I mean.
It downloads like 540 width all the time

**Comment by thomas694** [comment]
For text posts (not original photo posts) there's currently the problem that although Tumblr shows the big image on the page, their returned data structure only contains the med size image data.
If the problem persists the next days, we might need to additionally parse the html.

**Comment by wacher74** [comment]
I think the problem still exists.

**Comment by thomas694** [comment]
You can try this [test version](https://ci.appveyor.com/api/buildjobs/p43nbvvivkhial9h/artifacts/artifacts%2FTumblThree-v2.9.3-x64-Application.zip) to see if it helps.

**Comment by wacher74** [comment]
I'm afraid I don't see any changes.

blog url: 
	tumblr.com/liked/by/MY_ID

global 
  [X] Group photo set 
  
blog
  filename template is %i-%f

result
- lot of filename with leading dash, like "-5c36d0840f7e5f0662205b46907b8e4e4f8879"

photoset created by own:
"-7fdce9a0f6aa9e0ca50ac2e00f0fbe2086ca4"
"-08ace18c7f72f02d4ee6bc1625cd6d450dbc7"
"-494fbeeaf11010b2e385bbc5cd5b0c70c81dfb"

lot of "tumblr_" filename (but not all!) got dash
-tumblr_nvha9wZu2p1rgp2pjo1_1280
-tumblr_nvha9wZu2p1rgp2pjo2_1280
-tumblr_nvha9wZu2p1rgp2pjo3_1280

there is no image with good %i

**Comment by thomas694** [comment]
Well, the fix/version is only intended to solve the problem of this issue (missing higher res images).

**Comment by wacher74** [comment]
Really, my bad.
I got email notification, but I missed the subject.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
