### ISSUE TITLE
Settings never saved

### ISSUE THREAD

**Issue by over60geek** [TumblThreeApp/TumblThree#44]
Hello   I'm on 1.0.10.1008
Tumblethree is on a  computer  ,   blogs on an external hard drive 
I  recovered   blogs from another  computer   saved with a previous tumblthree who crashed on this previous computer   ( lost path ans settings on half the bolgs and some general settings

The problem is continuing with the newly installed tumblthree on this new computer : new settings are not saved   :  new path   new blog settings( download options)   I have to reset manually everything any time I run tumblthree

It seems the the new tumblethree is keepeing the old troubleshootings evenif it's not the same tumblethree version the same computer and the same harddrive for storage???
I can't find a clear path to a settings file which save the erronous informations to destroy them

Thanks for your work

**Comment by tehgarra** [comment]
I've noticed this sometimes also. It looks like it initializes with the default settings for some reason sometimes so I would wait and noticed that it return to my own settings. 

Not sure what causes this since sometimes I'll close it, and open it a few minutes later and it's fine.

**Comment by over60geek** [comment]
I  transfered the software on the same external Drive with the blogs  to make it portable.i scratched application data on my system  It improved  tumbltree  at the beginning. After two days tumbltree   writings destroyed my fat and i had to reformat my hard Drive. I lost. 2go.  So i m done with tumbltreeLe 28 mai 2019 10:31, tehgarra <notifications@github.com> a écrit :I've noticed this sometimes also. It looks like it initializes with the default settings for some reason sometimes so I would wait and noticed that it return to my own settings.
Not sure what causes this since sometimes I'll close it, and open it a few minutes later and it's fine.

**Comment by johanneszab** [comment]
Related to #61.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
