### ISSUE TITLE
Twitter blogs not downloading

### ISSUE THREAD

**Issue by tumblrdrei** [TumblThreeApp/TumblThree#442]
**Describe the bug**
My twitter blogs don't download anything anymore. 

**To Reproduce**
1. Click on Download
2. Add a previously added twitter blog that worked fine to the queue
3. Wait 
4. Download is "completed" but no files have been downloaded. 

**Expected behavior**
There are new posts on the twitter account, so there should be some downloads. 

**Desktop (please complete the following information):**
 - TumblThree version: [e.g. 2.10.2.399]
 - OS: [e.g. Windows 10 Home]
 - Browser [e.g. Chrome]
 - Version [e.g. the latest]

**Additional context**
It doesn't matter if it's an old or new twitter blog. None of my twitter blog are downloading anything.

**Comment by thomas694** [comment]
Is it still the case or was it a temporary problem?
Are the posts visible in the browser while being logged out?
If necessary send us an example blog together with "442" in the feedback dialog.

**Comment by Pleochism** [comment]
For me the affected blogs aren't viewable without being logged in due to NSFW. So it'd be nice to have a way to auth against Twitter like with the other platforms.

**Comment by fusionmc-evilscoop** [comment]
second this, all twitter blogs are now reporting as offline :(

**Comment by thomas694** [comment]
Now they have blocked public access to tweets. As a result the blogs are shown offline.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
