### ISSUE TITLE
Not downloading from a certain URL

### ISSUE THREAD

**Issue by curya** [TumblThreeApp/TumblThree#443]
**Describe the bug**
This website does not work with TumblThree: https://pizzacakecomic.com/

**To Reproduce**
1. Add https://pizzacakecomic.com/
2. Add to queue and try to download.
3. It doesn't work. Nothing gets downloaded.

**Expected behavior**
The pictures should download.

**Screenshots**

**Desktop (please complete the following information):**
 - TumblThree version: v2.10.2

**Comment by vozmor** [comment]
Hi @curya,

I think I have found a solution. 

1) When adding the url to TumblThree, it won't accept just "x.com" but "x.tumblr.com". This case, try adding https://pizzacakecomic.tumblr.com.

2) On the Details page of "pizzacakecomic" set the Crawler to Tumblr SVC instead of Tumblr API.

It worked for me with e.g. ofhouses.com.

**Comment by thomas694** [comment]
@curya 
Thanks for reporting a bug.
It will be fixed in the next version.

In the meantime you can use the solution suggested by vozmor, but please note that the blog name ends with "s" while the domain name does not, so use https://pizzacakecomics.tumblr.com/.

**Comment by curya** [comment]
Doesn't work no matter how I enter the URL.

https://pizzacakecomic.com/
https://pizzacakecomic.tumblr.com/
https://pizzacakecomics.tumblr.com/

I tried all three and nothing downloaded.

**Comment by thomas694** [comment]
Did you change the crawler type to "SVC" in the blog's settings page after adding the blog (https://pizzacakecomics.tumblr.com/)?

**Comment by curya** [comment]
@thomas694 That worked! Thanks!
Will it just be automatic in the next version? Or is this something I need to look out for in the future?

**Comment by thomas694** [comment]
Adding custom domains will work in the next version.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
