### ISSUE TITLE
Meta only saved/available for blogs

### ISSUE THREAD

**Issue by wongjustin99** [TumblThreeApp/TumblThree#45]
For Tumblr Tag Search/Likes, it seems not possible to download meta. 

Is that intentional?

I can only enable meta downloads in the "Details" tab when the site is a Tumblr blog.

**Comment by thomas694** [comment]
That information isn't available in the crawled data and would make it necessary to do another request for each shown post to download the real meta data.
I'm not sure if that makes much sense.
But anyone who wants to implement it as an option is welcome.
