### ISSUE TITLE
Images with non "tumblr_" urls don't seem to be downloading from blogs

### ISSUE THREAD

**Issue by tehgarra** [TumblThreeApp/TumblThree#47]
I'm not sure if it's specifically related to #19 or #27, but I've never noticed the url looking exactly like this before

```
https://66.media.tumblr.com/cd813bc6ec731b7057f6f250ae13d587/tumblr_pusoqc8FmZ1uw3f6jo1_1280.jpg
https://66.media.tumblr.com/cfafe79f6a7713098cea73103d5bd647/171e761be99622dd-92/s1280x1920/cd36d02b9327562f651244930596cdaeb2871b6a.png
```
the first link works fine, but the second link, doesn't show up in the files despite being the newest image posted on the blog. am I doing something incorrect? i've tried with another blog and i've been unable to get the files that have that same type of url

**Comment by ManekiNeko-89** [comment]
I'm the same as you, I have exactly the same problem with URLs of images that don't contain tumblr_.
