### ISSUE TITLE
Twitter Crawler has been using "Name" instead of "ScreenName" for reblogs since data structures changed

### ISSUE THREAD

**Issue by deege216** [TumblThreeApp/TumblThree#473]
Not a huge deal ... but I noticed that several versions back the Twitter crawler began replacing %o with the blog's full "Name" (which is not unique and can change) instead of the previous "ScreenName".  If that wasn't intentional, then it's a quick and easy fix on line 978 (version 2.11.3.0) of TwitterCrawler.cs.  I changed my own but I wouldn't want to mess anything up in case that was a planned change. :)

**Comment by thomas694** [comment]
You're right. That was unintentional. Would you like to contribute a PR?
