### ISSUE TITLE
[request] jar version of tumblthree

### ISSUE THREAD

**Issue by Norithiel** [TumblThreeApp/TumblThree#49]
Hi there! Is there any chance to release the *.jar version of tumblthree? 

I've been using tumblthree for several years and this this is the best image grabber ever! Thank you for supporting this project for so long! I moved to os X and found no chance to open *.exe file there.

**Comment by johanneszab** [comment]
hi Norithiel,

unfortunately it's not possible to just repack TumblThree into a .jar file. Jar files are used by Java Applications, TumblThree is a CLI/.NET (C#) application.

Microsoft is currently actively bringing C# to other operating systems after the acquire of Xamarin and with its .NET core strategy. With some(?) specific macOS code it might even be possible (soon, now?) to bring TumblThree to macOS. [See this post on MSDN about Xamarin.Mac](https://docs.microsoft.com/en-us/xamarin/mac/get-started/hello-mac).

I haven't looked into this however. If anyone is interested in this, maybe it will happen.
