### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by johnflint1985** [TumblThreeApp/TumblThree#52]
I have constantly en error 429 limit exceeded. no matter what I do it gives me the same error. I tried to make a number of API connections lower, but it didn't work

**Comment by Klimax** [comment]
Pretty sure this is duplicate of this issue:
https://github.com/TumblThreeApp/TumblThree/issues/46

**Comment by johanneszab** [comment]
I guess so too. Hence, please refer to the other issue.
