### ISSUE TITLE
Data loss occurs when "access denied" videos replace local files if index files are not present to force skipping.

### ISSUE THREAD

**Issue by xion2** [TumblThreeApp/TumblThree#53]
So I think i've discovered some possibly unwanted behavior. I wanted to see if it was safe to reload blogs without their index files and re-scan. I found that it is NOT safe and data loss WILL occur in specific circumstances and it could get much worse if Tumblr changes how pictures are pointed to.

So here is what I did. I found a NSFW blog that I know for a fact has "access denied" videos on it and that I had a local version of from months ago where the videos were still working. Then I ran the following tests:

**Test 1:** Placed old downloaded files along with old index files into new directory then ran the re-scan.
**Result:** Index files were updated to reflect the current post count. Which is a bit annoying and misleading but the local files were not touched. Ran multipar and verified all files were intact and not touched other than index files which got updated.

**Test 2:** Placed old downloaded files into folder WITHOUT index files and did a full blog re-download.
**Result:** Any videos currently listed in the blog with "access denied" attempted re-download but failed and local copies were DELETED.

I'm not sure whether this only happens with videos or if it can happen with images as well.

However, if tumblr started to change access to full URL images on a widespread scale it could be very bad. Someone trying to re-download blogs without index files could suffer catastrophic data loss. Millions of backed up files gone in an instant because no index files to tell the program not to touch anything in the local folders. Even with index files i'm not comfortable updating my blogs right now just because how the software handles local file disputes.

I'd recommend some sort of software update adding a feature to "backup old files" with different file sizes so that error pages, access denied pages or any other kind of replacement image/video never replace local files. Then the user can choose which file they want to keep, assuming anything is saved at all. In this case nothing is actually saved and so the only file left would be the working one. Though it might end up re-named in the process that's still better than outright deletion.

**Comment by thomas694** [comment]
This one looks solved months ago. Else we would need an appropriate example blog and/or video url which produces that behaviour.
It has been closed, but can be reopened if needed.
