### ISSUE TITLE
Cannot download conversation posts in txt mode.

### ISSUE THREAD

**Issue by PixlRainbow** [TumblThreeApp/TumblThree#530]
**Describe the bug**
When tumblthree downloads a conversation post (on Tumblr) with output set as txt, it does not properly stringify the content of the post; it saves a .NET object class name instead.

**To Reproduce**
1. Add a blog containing old conversation posts.
  I used sleufoot, but this blog will be deleted within the next few hours.
2. Make sure "download conversation posts" is checked in blog details.
3. Add blog to queue and start download.
4. See "conversations.txt" in output folder.

**Expected behavior**
Conversation posts are converted into HTML unordered lists and saved in conversations.txt

**Screenshots**
[conversations.txt](https://github.com/TumblThreeApp/TumblThree/files/15288883/conversations.txt)  
*Example:*  
```
Post id: 144817631650
Date: 2016-05-23 18:59:36 GMT
Post url: https://sleufoot.tumblr.com/post/144817631650
Slug: interviewer-so-what-can-you-do-what-are-your
Reblog key: Yt0iU3Dn
Reblog url: 
Reblog name: 
Quote: System.Linq.Enumerable+WhereSelectListIterator`2[TumblThree.Applications.DataModels.TumblrApiJson.Conversation,<>f__AnonymousType0`2[System.String,System.String]]
Body: 
Tags: 
```

**Desktop (please complete the following information):**
 - TumblThree version: 2.13.0.442 (release)
 - OS: Windows 10 Home
 - Browser: Firefox
 - Version 125.0.3 (64-bit)

**Additional context**
Download was attempted on very old Tumblr posts from 2016.

**Comment by thomas694** [comment]
Thanks for reporting a bug. We'll take a look at it.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
