### ISSUE TITLE
Now that X formally changed its domain name to X.com from Twitter. The Twitter download feature has stopped working. 

### ISSUE THREAD

**Issue by Nightshade009** [TumblThreeApp/TumblThree#532]
Now that Elon Musk has formally changed the domain from Twitter to X.com. The Twitter feed download and add feature for TumblThree App has stopped working. I'm wondering will this be fixed in new updates, or is TumblThree no longer supported? 

Right now, you can still download from Twitter feeds. But you must manually change the URL from X.com to Twitter.com in the feed address box. But I understand this 'backdoor' will soon close.

**Comment by thomas694** [comment]
Well, I guess we'll fix it.

**Comment by bloke90** [comment]
it doesn'T work anymore with replacing "x" with "twitter" (I'm logged in)

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.

**Comment by bloke90** [comment]
v2.14.0 still says "twitter blog is offline" - I delered and added again (no automatical adding as with tumblr or twitter before)

**Comment by deege216** [comment]
All blogs show 403 Forbidden.  I believe the problem is the cookies.json file - I manually opened the file, replaced all "twitter.com" with "x.com" and re-ran the app and everything is processing correctly.

**Comment by bloke90** [comment]
in index file still .twitter is used... I delete the twitter names in index file but the return wiht ".twitter" after adding ".x" in UI

**Comment by Nightshade009** [comment]
The only workaround I've found is going back to the previous version.  And for now on, when I go to add a new X feed.  I have to manually change the X url back to Twitter.com. Otherwise, if I go, continue downloading. It simply says “offline” to any feed I try to download.  And at this point, I'm not willing to delete all my index list and start over from scratch! So previous version it seem it shall be for the time being.

**Comment by deege216** [comment]
I don't think going back to the previous version is needed.  The new version replaces twitter.com with x.com in your index files (you may have to close the app and let it re-save the files to show that).  It's just the cookies file that doesn't have the new x.com in it - and you can open that in a text editor and search-and-replace it yourself.  I'm running the latest 2.14 and it's downloading Twitter sites just fine with the cookies change.  If you don't do that, you'll get offline errors for every blog.

**Comment by thomas694** [comment]
You are right, @deege216.
The new version removes an no longer needed cookie and renames the other ones. Either this is already enough or the user has to login once again, e.g. anyway expired cookies.
I thought this approach was better in any case than simply deleting all the cookies.

It works now again?

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
