### ISSUE TITLE
Can't Download tumblr likes anymore. 

### ISSUE THREAD

**Issue by azizomar9** [TumblThreeApp/TumblThree#539]
**Describe the bug**
For the past two to three weeks, I haven't been able to download my tumblr likes anymore. Everytime I attempt it, it says Error 1: Likes: Error Parsing Post!

**To Reproduce**
1. Try to download your likes blog. 
2. See error

**Expected behavior**
It is supposed to download all the photos/videos that are in my likes. 

**Desktop (please complete the following information):**
 - TumblThree version: 2.13
 - OS: Windows 10

**Comment by thomas694** [comment]
Thanks for reporting a bug. We'll take a look at it.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
