### ISSUE TITLE
Completely has stopped working on Twitter/x since upgrade yesterday.  

### ISSUE THREAD

**Issue by Nightshade009** [TumblThreeApp/TumblThree#547]
Completely has stopped working on Twitter/x since upgrade yesterday.  Shows all threads/blogs as offline and won't allow downloads. 

Is there anywhere I can get the previous version before the upgrade? I'd like to downgrade to that one again, since it worked with minor manual adjustment.

**Comment by ErikBrown2** [comment]
You can download older versions here: https://github.com/TumblThreeApp/TumblThree/releases
In case you do not see any files listed under Assets for a certain release, then you can click on the arrow in frond of the word Assets and the files will be shown.

**Comment by thomas694** [comment]
It's fixed in the new version.
