### ISSUE TITLE
Image size couldn't be retrieved

### ISSUE THREAD

**Issue by johnflint1985** [TumblThreeApp/TumblThree#552]
Image size couldn't be retrieved.

I am not sure what is this but it shows for every single blog now
![ERROR 4532](https://github.com/TumblThreeApp/TumblThree/assets/29380159/0c036d01-9c5d-4f5a-9098-11c6d162da24)

Please advise!

**Comment by thomas694** [comment]
There exists already a discussion about it, #551

It seems the page structure changed. We'll fix it.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
