### ISSUE TITLE
Cannot crawl links that use Tumblr Tag Search

### ISSUE THREAD

**Issue by SkylerBlu9** [TumblThreeApp/TumblThree#553]
**Describe the bug**
Attempting to crawl tumblr.com/tagged/TAG type links appears to fail

**To Reproduce**
1. Attempt to search for a tag via URL and download the images. (EG. https://www.tumblr.com/tagged/kasane%20teto)

**Desktop (please complete the following information):**
 - TumblThree version: 2.14.1
 - OS: Windows 11
 
No error message is thrown, the link simply gets put in the queue, sometimes says "Calculating unique downloads, removing duplicates...", then disappears from queue without downloading any images.
 
[log.txt](https://github.com/user-attachments/files/16114564/log.txt)

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
