### ISSUE TITLE
Preview of images during downloading causes an error

### ISSUE THREAD

**Issue by ErikBrown2** [TumblThreeApp/TumblThree#569]
**Describe the bug**
If you queue some blogs for download, start the downloads and enable Details - Preview of the currently downloaded blog, then the downloaded images will be shown. But almost always this will result at some point in an error. When this happens, then for a few seconds nothing is changing on the screen. And then suddenly multiple blogs are highlighted in green. Blogs are then not downloaded anymore.

It will happen almost always when I select multiple blogs to be downloaded with the preview option enabled. Some blogs will download successfully but at some point this error occurs. The error does not happen when I do not select the preview option.

This issue is not new, it has been happening for over a few years.

**To Reproduce**
1. Queue multiple blogs for download
2. For the first blog select the preview option 
3. Start the downloads
4. Click on the blog highlighted in green to start previewing the images
5. Wait till the error occurs

**Expected behavior**
That the downloads work fine, also with the preview option enabled.
**Screenshots**

<img width="960" alt="Screenshot 2024-09-08 153405" src="https://github.com/user-attachments/assets/00d18e56-ba48-467f-bf08-b38dfd375955">

**Desktop (please complete the following information):**
 - TumblThree version: 2.15.1.462
 - OS: Windows 10 pro 
 - Browser: Firefox
 - Version 130.0

**Additional context**

**Comment by thomas694** [comment]
Then you should have reported it earlier 😉
Do you see any error message in the log when this happens?

**Comment by ErikBrown2** [comment]
Just some more info about this issue. When I queue only blogs with the type Tumblr and preview them while downloading, then the issue of the multiple green blogs does not show up. It works then without any issues.

Another issue (but still related, I assume) shows up when I select the blogs with the type Tumblr hidden and Tumblr tag search (so not the regular Tumblr blogs). When I do not preview them, then the download completes and all four blogs are removed from the queue. The below screenshot shows the screen before the download.

 
<img width="960" alt="Screenshot 2024-09-21 235455" src="https://github.com/user-attachments/assets/54d4dc41-f963-418d-9850-8ba6912a1a5b">

Still a log was created. This is the log after the successfully completed check of these four blogs (without preview)
[TumblThree without viewing.log](https://github.com/user-attachments/files/17085904/TumblThree.without.viewing.log)

But when I select preview and try to download the four blogs, then only the first blog is removed from the queue and then the download stops.

<img width="960" alt="Screenshot 2024-09-22 000416" src="https://github.com/user-attachments/assets/bdb13262-ed85-4796-8632-f940f3b8d330">

If I then check the queue, then this is shown:

<img width="960" alt="Screenshot 2024-09-22 000448" src="https://github.com/user-attachments/assets/3230ae7e-d47a-4abc-9cfc-1411512d1001">

This is then the log:

[TumblThree when download stopped after the first blog.log](https://github.com/user-attachments/files/17085915/TumblThree.when.download.stopped.after.the.first.blog.log)

**Comment by ErikBrown2** [comment]
In case you want to test with the same blogs as I did, here is the exported blog list:

[MyBlogsBackup.txt](https://github.com/user-attachments/files/17085952/MyBlogsBackup.txt)

**Comment by thomas694** [comment]
Please try this [test version](https://ci.appveyor.com/api/buildjobs/s36fk93k2ex20ntu/artifacts/artifacts%2FTumblThree-v2.15.1-x64-Application.zip) to see if it solves the problem.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
