### ISSUE TITLE
New files will be downloaded?

### ISSUE THREAD

**Issue by wacher74** [TumblThreeApp/TumblThree#58]
1) Since tumblr introduced the new naming conventions ThumblTree misses lot of files of new posts.
Older post are still working.
When TumblrThree will be fixed to handle new naming, it will be download now skipped files?
2) Last file remains opened by TumblrTree therefore I can't delete it unless I close TumblrTree.

**Comment by ErikBrown2** [comment]
Is TumblThree still maintained? I have unfortunately not seen updates for a long time,

**Comment by johanneszab** [comment]
Hi, thanks for your comment.

To 1:
I think @ShadowBlade72 already fixed this in #48. I'll upload a new version this evening which hopefully will get all your posts. I've only briefly tested it with images, and it looked like grapped all of then. But I haven't used tumblr or TumblThree for over a year. It it still misses anything, please be more specific than "new naming conventions".

To 2: Yes, I've noticed that too but the pain was never that big that I bother to fix it, especially as there are -- imho -- plenty of more important issues/requests. But again, thanks for telling! At least we have an open issue for this now.

**Comment by wacher74** [comment]
Thank you :)
