### ISSUE TITLE
Will you make a new downloader for Twitter?

### ISSUE THREAD

**Issue by AIRDOGE** [TumblThreeApp/TumblThree#59]
Tumblthree is very good.Twitter needs a good downloader.

**Comment by wacher74** [comment]
This one seems abandoned, too.

**Comment by ErikBrown2** [comment]
> This one seems abandoned, too.

Yes, unfortunately

**Comment by johanneszab** [comment]
Probably not. But feel free to submit code. TumblThree actually already contains four different "downloader".
For example the Tumblr Search scraping is vastly different than the non-public/hidden Tumblr blog scraping routine. Hence, you should be able to use several of the existing parts. And refactoring is also always welcomed ;-).

**Comment by AIRDOGE** [comment]
Thanks for your reply！

**Comment by johanneszab** [comment]
Well, for what its worth, I'll leave this open as someone else also suggested a twitter downloader here #41.
