### ISSUE TITLE
not downloading webp images and webm videos

### ISSUE THREAD

**Issue by thecbloom** [TumblThreeApp/TumblThree#60]
webp and webm are becoming common and should be added.  Not sure if it's here :

R:\z\TumblThree-1.0.11.2\src\TumblThree\TumblThree.Applications\Parser\ImgurParser.cs(28) : public Regex GetImgurImageRegex() => new Regex("(http[A-Za-z0-9_/:.]*i.imgur.com/([A-Za-z0-9_]*)(.jpg|.png|.gif|.gifv))");
R:\z\TumblThree-1.0.11.2\src\TumblThree\TumblThree.Applications\Downloader\AbstractDownloader.cs(33) : private readonly string[] suffixes = { ".jpg", ".jpeg", ".png" };

**Comment by johanneszab** [comment]
Might be fixed with most recent version. I don't know of any blogs with webp / webm content, hence I couldn't test it.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
