### ISSUE TITLE
Settings not updated after crash

### ISSUE THREAD

**Issue by ErikBrown2** [TumblThreeApp/TumblThree#61]
First thank you very much for the recent update. TumblrThree is used by lots of people and it is great to see that it is still maintained.

Sometimes TumbleThree hangs during downloads and all modifications that were made during the session to the blog settings will be lost. I tried now two times to change the crawler type of all my blogs to tumblrpriv but after completing some of the blogs the program exited abnormally and the updated index info was not saved. The program hans during download and when you exit, it does so without saving the indexfiles. The crash is not my point here, but the time of saving the modified index files.

 I know that I could make the modifications without downloading and then restart the program so that the changes are saved. But would it not be possible to save the files immediately after changes are made and not wait till exiting the application? That would make the file updates much more reliable.

**Comment by johanneszab** [comment]
I'll change the code so that the settings are stored to disk after closing the settings window (by pressing the "save" button). Looks like as if it's possible with just a few lines of code.

Thanks for the suggestion! Should be in the next release.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
