### ISSUE TITLE
Download stops on some blogs when using the Tumblr SVC crawler

### ISSUE THREAD

**Issue by ErikBrown2** [TumblThreeApp/TumblThree#63]
Using the new SVC crawler, downloading sometimes stops. The program is still responsive in a way that you can do other things like checking the configuration settings etc. but downloading does not continue. The behavior for blogs that cause this is as follows:

The downloads for the previous blog in the queue are finished and the next (problem) blogs is selected for crawling. The blog entry in the left side list becomes green, the blog name in the queue list becomes blue but further nothing appears to happen. If I then click on stop, then the program exists without error message. Data like the progress for previously crawled blogs, modifications that I made to other blog settings etc are then not saved.

As a sample, the blog https://guttx.tumblr.com/ causes downloading to stop. My internet provider blocks access to some blogs by re-directing them to another URL. This also triggers this issue. The Tumblr API crawler does not have this issue and just continues with the next blog in the queue when it tries to crawl these blogs. 

I am using version 1.0.11.4 but it happens since the SVC crawler was newly implemented.

Would it be possible to have some kind of extra checking in the SVC crawler that avoids the crawler to stop?

**Comment by ErikBrown2** [comment]
Edit: Found that the SVC crawler also hangs randomly on a blog. The blog was part of several blogs in the queue and it had become the first in the queue. It was not highlighted in green in the left list and it was still shown in black in the queue list. Pressing on stop caused the application to exit without error message. When I tried the same blog again, it worked fine.

**Comment by johanneszab** [comment]
hi there!

Thank you a lot for that valuable information and detailed descriptions. I could really limit the possible issues based on your input to just a few code spots.

I'm pretty sure about having fixed your second comment, but I'm not fully certain about your first described issue. I could not fully reproduce it. Thus, if you have a way to reproduce those issues to a certain degree, I'd like to upload some TumblThree version you could test which hopefully fix all of your described bugs.

I'll start with a version that should fix all of your issues of the second comment -- I could easily reproduce those -- and maybe the issue of your first comment.

[TumblThree-v1.0.11.5-test-Application.zip](https://github.com/TumblThreeApp/TumblThree/files/4215092/TumblThree-v1.0.11.5-test-Application.zip)

**Comment by johanneszab** [comment]
I'll see some more into the code now. If I find some other spots which might not handle (improper) input gratefully, and hence stall, I'll upload another version you could test.

**Comment by ErikBrown2** [comment]
Thank you very much for the quick update. I have tested it with the problem blogs and it works fine now. I will keep it running to see if also the random stops are solved. Again, thanks for the update!

**Comment by ErikBrown2** [comment]
I have left the application crawling since yesterday. It has been running correctly now for almost 24 hours so it looks like it is stable now.

**Comment by johanneszab** [comment]
Thanks for testing!

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
