### ISSUE TITLE
Tumblr Tag Search and Tumblr Search Only Returns With 1 Result

### ISSUE THREAD

**Issue by TheJyaki** [TumblThreeApp/TumblThree#69]
There should be more than one result. Downloading blogs works just fine, but I can not download by  tags as only one result shows up.

Apologies if this is something I have had an oversight of. I've been looking online for a solution for awhile and have not found anything.

**Comment by johanneszab** [comment]
True.
It looks like the authentication process and sending the search requests still work, but the actual received search response with a tumblr valid login has changed.

However, if you log out yourself within TumblThree (Settings->Connection->Log out) and perform the "search crawl" as anonymous, it still works.

For example here https://www.tumblr.com/search/music I can download 453 images/videos as anonymous.
