### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by elipriaulx** [TumblThreeApp/TumblThree#7]
Find a home and process for creating documentation. This doesn't need to entail creating documentation, but at the least, determine how documentation will be available in the future, how people can contribute, and create issues to create documentation that can be absorbed into future milestones.

**Comment by gpriaulx** [comment]
Ever used a static site generator like Wyam.io, or jekyllrb? Would these be appropriate here?

**Comment by gpriaulx** [comment]
Since this issue has been quiet, I'll look into using Wyam for documentation, and setting up a CI pipeline to build it to github pages or something similar.
