### ISSUE TITLE
Log in sometimes fails with right credentials (TumblThree doesnt handle captchas)

### ISSUE THREAD

**Issue by lostthecode** [TumblThreeApp/TumblThree#73]
I am having trouble getting the tumblr log in to work in the app but every time i try it asks for TFA, i give it all the codes tumblr gives me and none work.

**Comment by ragingfred** [comment]
Keeps asking for a TFA even when it is disabled on the account.

**Comment by johanneszab** [comment]
If you happen to have to solve a recaptcha during the login process, then TumblThree will incorrectly ask for a TFA and fail because nothing is implemented for solving captchas.

You might to try to reconnect to you ISP to get a fresh IP and see if that fixes the issue.

**Comment by jasonhouston** [comment]
How is the app storing these cookies?  I cannot get around this issue, even with connecting through a different WAN IP.

**Comment by thomas694** [comment]
At the moment a browser control is used for login in so this shouldn't be a problem any more.

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.
