### ISSUE TITLE
Blog Offline vs Hidden Blog

### ISSUE THREAD

**Issue by calves07** [TumblThreeApp/TumblThree#76]
What's the difference really? There are hidden blogs that appear Online / Hidden but others appear Offline...

**Comment by amorakfd** [comment]
I noticed that today too. In general "offline means the blog is down, but yet blog is still active! Occurs with some hidden blog, not all. Did tumblr change something in the way tumblthree access to API? in fact download is no more possible when status is found "offline" by the program.

**Comment by amorakfd** [comment]
Now tumblr must be satisfied because they no longer be viewable in tumbex! I think this is their final goal.

**Comment by amorakfd** [comment]
It seems to affect some hidden blogs by now, but I'm really afraid tumblr expands this blocking to all flagged blogs! maybe next step?
