### ISSUE TITLE
Strange problem with API/SVC and some restricted blogs

### ISSUE THREAD

**Issue by Gonched** [TumblThreeApp/TumblThree#77]
I've been using TumblThree to download a variety of blogs including some that became restricted (rude content) after I added them, and some that were restricted before I added them. I've always used Tumblr API as the default and didn't have a problem.

Within the last two weeks, TumblThree has been flagging some of these blogs as offline when they're still accessible on Tumblr.  Changing the crawler to SVC, TumblThree reports the blogs as online but any attempt to crawl these blogs causes TumblThree to immediately lock up or lock up after downloading a few images.  By 'lock up' I mean the crawl stops but the UI still responds.  Any attempt to pause or stop the crawl freezes the UI too.  This is happening with 1.0.11.6 and 1.0.11.7.

One blog that this is happening with is ilikelittle22 (reasonably benign).

**Comment by calves07** [comment]
Most likely a duplicate from my issue (#76 )

**Comment by johanneszab** [comment]
Hmm, that particular blog there seems to work for me, no lock up, its not been shown as offline. I've added two other blogs, set them all to "Tumblr SVC" via the Details panel, and started downloading them all. No hanging.

Thanks however for providing a small example blog.

I'm guessing that maybe now that most people are actually using the "SVC crawler" that maybe the servers might sometimes respond irregular, or maybe they are even rate limiting access like the Tumblr V1 API. I've already found code which will react how you describe it if the server answered in a way I didn't anticipate it.

I'll add some more safe guards in that respect sometime later this week and might add some file debug logging to log all the exceptions you will get. Maybe that does help debugging it.

If you encounter an offline blog that is actually online, can you re-online it by pressing right button in the manager after selecting the blogs (via shift + blogs, or strg + blogs) and clicking "check blog online status"? If it's a hidden blog/dashboard blog which nowadays is opened awkwardly using a fraction of the screen on the right side on Tumblr, it's probably only accessible via the SVC crawler. Hence, you'll have to change the Crawler type in the details panel beforehand.

**Comment by Gonched** [comment]
Thanks for looking into this.

I've been using the "check blog online status" option to re-enable the blogs after switching them to SVC.  After the re-enable is when the crawl fails.  BTW, I tried downloading the example blog with Tumblripper and it failed too.

As calves07 mentioned above, this seems to be same problem as he was having.  I think Tumblr changed the rules again.

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.
