### ISSUE TITLE
Add delimiting commas between objects when saving blog metadata as JSON

### ISSUE THREAD

**Issue by mamift** [TumblThreeApp/TumblThree#82]
Currently, when choosing to save blog metadata as JSON, it saves the metadata as text files, but for some reason omits delimiting commas for individual post objects (after the `}` closing off one object, but before another `{` beginning a new object). It does add them for individual object properties. Here's what I mean (taking an excerpt of `images.txt`):
```JSON
{
  "video-player-500": "",
  "video-source": "",
  "width":  937
}

{
  "answer": "",
  "audio-capt: "",
}
```
To view all instances in a text editor, the regex search for it is: `}\n{`.

Is it possible to implement a change to add those delimiting commas when downloading a Tumblr blog using JSON as the metadata format? This would make it more parsable.

**Comment by thomas694** [comment]
At the moment only delimiting commas have been added, because array brackets would need a bigger code change.
So, if you want to use the JSON files in another program or JSON editor, you have to remove the last comma and put brackets around the whole content.

**Comment by thomas694** [comment]
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.
