### ISSUE TITLE
TFA not allowing login

### ISSUE THREAD

**Issue by GregoryWest501** [TumblThreeApp/TumblThree#83]
I know this is bush league but I am not able to get past the TFA box.  I didn't have TFA turned on on tumblr, but I am still being asked for a code.  I turned it on, got a whole bunch of codes, but none of them seem to work.  How do I get past this?

Greg

**Comment by Rochusberg** [comment]
Same problem here. See also discussion here: https://github.com/TumblThreeApp/TumblThree/issues/81
