### ISSUE TITLE
TFA detected

### ISSUE THREAD

**Issue by jjdnl** [TumblThreeApp/TumblThree#85]
As of today i get the message TFA detected when i try to log in to my tumblr in ThumblTree. But i don't use TFA, and never have done so.

ThumblingJAzz, for automatic posts, can login to my Tumblr, so i guess the problem lies in ThumblThree.
Any suggestions?
Using version 1.0.8.76

**Comment by ErikBrown2** [comment]
It appears that there is hope for a quick fix. See this https://github.com/TumblThreeApp/TumblThree/issues/81#issuecomment-693193748

**Comment by thomas694** [comment]
See discussion here: #81

A new version has been released:
https://github.com/TumblThreeApp/TumblThree/releases/tag/v1.0.11.9
