### ISSUE TITLE
Technical Writer wanted

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#93]
Who has technical writing skills and wants to write user documentation for the TumblThree application?

The goal would be to have an user documentation for explaining the functionality of the TumblThree application, as well as a website that attracts more people to TumblThree.

Subtasks for a start would be something like:
- gather and combine the information from the different repositories, wikis and old website and update it
- evaluate whether [GitHub Pages](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/getting-started-with-github-pages) are enough for the task or an additional tool like [Wyam](https://wyam.io) is necessary or provides benefits
- evaluate if its possible to create eg. a PDF out of the Markdown code or an online-only version should be enough
- write the user documentation and web site content
- the source of the documentation and/or web site shall be easily editable and manageable through a repository

Subtasks are subject to slight changes as the evaluation progresses.

Do you like to support us and make a contribution? Your help is greatly appreciated.

**Comment by DeerTears** [comment]
I just ran into this project for the first time, and I've never seen a more inviting github issue in my life until now. Technical writing is a hobby for me and I would love to dig into this.

Now, I can't guarantee I can get on this right-away because right now I'm a full time student learning graphic design. I also just learned how github pages work this month, so I can't promise anything other than enthusiasm and some content for these docs later down the line. I'll happily get back project to this when my schedule allows it.

**Comment by thomas694** [comment]
Hello Ember,
thanks for your interest in participating in the TumblThree project.
We are all volunteers here, you set the pace. Your enthusiasm is a good starting point and we are looking forward to your support. Besides good luck for your studies. We'll be happy to hear from you.
Stay safe, stay healthy.

**Comment by thomas694** [comment]
For the moment we created another branch `gh-pages` and added an adapted version of Johannes's original blog post about TumblThree so that this project will hopefully get more present in search engines in the future.
The url of the page is: [https://tumblthreeapp.github.io/TumblThree/](https://tumblthreeapp.github.io/TumblThree/)

Does it make any big difference if a branch (shortest possible url: [https://tumblthreeapp.github.io/TumblThree](https://tumblthreeapp.github.io/TumblThree)) or a separate repository (shortest possible url: [https://tumblthreeapp.github.io](https://tumblthreeapp.github.io)) is used for the GH Pages?

**Comment by Manasi-Kelkar** [comment]
Hi, I can help you with user documentation. I want one confirmation, whether this issue is still open or m I late?

**Comment by thomas694** [comment]
Hi,
thanks for offering your help. Yes, this issue is still open. As you can see above someone has already offered her help, but she hasn't had time yet the last few months.
So, if it's ok for you, I would suggest that I assign it to you and you can start working on it. And if she finds time later and would like to join, we can have a look and see how far we got and what is still left. For sure we'll find a way how to split up the work then or she can work on other related parts.
What do you think?

**Comment by Manasi-Kelkar** [comment]
It sounds good to me. Please assign the work so I can start working on it.

**Comment by thomas694** [comment]
Please get yourself familiar with the different structures and repositories of the TumblThree family. Later it would be nice if you give a short note on which point/task you want to start.
If at any time you have questions, let me know.

**Comment by Manasi-Kelkar** [comment]
Yeah, sure.

**Comment by thomas694** [comment]
Thanks to @Manasi-Kelkar for redesigning our [web page](https://tumblthreeapp.github.io/) and giving it a fresh new layout.

**Comment by thomas694** [comment]
This issue is open for new volunteers who like to continue on this topic.

**Comment by Someonemustnothavethis** [comment]
Those of you who might be writing a manual for this,  please remember that many users are NOT programmers or 'geeks' and need
it to be straight forward with no technical jargon.   An example is how to update the program.  I have over a dozen sub-directories in my installed directory, each one labeled "1.3.2, 1.4.1, 1.4.5, etc.  I don't know if this is how I'm supposed to install updates, but it's working.    Simple instructions for this would go a long way towards making this program much more accessible to the average person.
   Thanks.
     Rob
