### ISSUE TITLE
Crawler data json files updated for old blogs

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#98]
**Describe the bug/problem**
Often times when a blog (with the option "dump crawler data") is crawled a few files inside the blog's folder have a new time stamp even if the blog hasn't had any post for a while.

**To Reproduce**
1. Enable "Dump crawler data" for some blogs and crawl them completely once
2. Inspect the files in the blog's folder
3. Crawl one or more of the above blogs again
4. Check the json files in blog folders

**Expected behavior**
For old blogs which don't have a new post the crawler should not have to update any files after one complete crawl, because there is nothing to download and even the crawler dump data (the post data) itself shouldn't change unless you enable the "Force rescan" option.

**Desktop (please complete the following information):**
 - TumblThree version: 1.0.11.12
 - OS: Win 10

Does anyone know what is going wrong in the code? Do you know how to solve it?

**Comment by thomas694** [comment]
Additionally while downloading/saving the crawler data System.IO.IOExceptions "The process cannot access the file '<file path>' because it is being used by another process" can occur.

**Comment by thomas694** [comment]
[As before](https://github.com/TumblThreeApp/TumblThree/issues/101) this one is for first-timers-only. That means that we will only accept a PR for this one from someone who's never contributed to open source before. This one is particularly easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). We walk you through it if you need help. :-) Here are the steps to get a PR merged here (see also our [guide](https://github.com/TumblThreeApp/TumblThree/blob/master/Contributing.md)).

For normal files (e.g. photos) the downloader checks if the photo's filename already exists in the database ([CheckIfFileExistsInDB](https://github.com/TumblThreeApp/TumblThree/blob/a99f8e602c4bcad39ccd9a49b0b8e94407918f4d/src/TumblThree/TumblThree.Applications/Downloader/AbstractDownloader.cs#L279)) or if the file already exists in the directory ([CheckIfFileExistsInDirectory](https://github.com/TumblThreeApp/TumblThree/blob/a99f8e602c4bcad39ccd9a49b0b8e94407918f4d/src/TumblThree/TumblThree.Domain/Models/Blogs/Blog.cs#L907)). But for the json crawler data it is only checked if the blog's  [setting](https://github.com/TumblThreeApp/TumblThree/blob/a99f8e602c4bcad39ccd9a49b0b8e94407918f4d/src/TumblThree/TumblThree.Applications/Crawler/TumblrBlogCrawler.cs#L427) "dump crawler data" is enabled or not, and no checks if the post's crawler data file already has been downloaded before and exists. Hence they are saved to disk again, overwriting the old file and giving it a new timestamp. That's not necessary because as an old post cannot change and therefore its source json which is saved as the crawler data also not.
While dumping crawler data for photos System.IO.IOExceptions can additionally happen, because normally the post's main photo and the first entry in the post's photo array are the same image (look at the source of an image post). So sometimes the crawler data is "downloaded" and tried to save by two threads in parallel, but of course only one thread can access the file at one time.

- [x] Create a fork of the repository
- [x] Clone it to your local disk and create a new branch (e.g. 98-crawler-data-json-files-updated)
- [x] Look what class and methods are used to remember already downloaded [files](https://github.com/TumblThreeApp/TumblThree/blob/ce7a675a9e2a74ab135ed24b72b6653567ec0f43/src/TumblThree/TumblThree.Domain/Models/Files/Files.cs) and how they are called. Could this be used and adapted for checking already downloaded crawler data?
- [x] Start with e.g. the [TumblrBlogCrawler](https://github.com/TumblThreeApp/TumblThree/blob/a99f8e602c4bcad39ccd9a49b0b8e94407918f4d/src/TumblThree/TumblThree.Applications/Crawler/TumblrBlogCrawler.cs). The crawler could fill an internal list with all the *.json filenames inside this blog's directory right before the method for the download of the crawler data is called.
- [x] Whenever a crawler data file shall be saved it has to be [checked](https://github.com/TumblThreeApp/TumblThree/blob/a99f8e602c4bcad39ccd9a49b0b8e94407918f4d/src/TumblThree/TumblThree.Applications/Crawler/TumblrBlogCrawler.cs#L427) if it really needs to be saved. Keep in mind what has to be done for "forced rescans"
- [x] Add your solution also to the [TumblrHiddenCrawler](https://github.com/TumblThreeApp/TumblThree/blob/a99f8e602c4bcad39ccd9a49b0b8e94407918f4d/src/TumblThree/TumblThree.Applications/Crawler/TumblrHiddenCrawler.cs) and [TumblrTagSearchCrawler](https://github.com/TumblThreeApp/TumblThree/blob/a99f8e602c4bcad39ccd9a49b0b8e94407918f4d/src/TumblThree/TumblThree.Applications/Crawler/TumblrTagSearchCrawler.cs)
- [x] Build the app and run it
- [x] Crawl a blog (with "dump crawler data" enabled)
- [x] Check if the above mentioned exceptions still occur. Do the crawler data json files still get updated?
- [x] Commit your changes mentioning "issue #98" somewhere in your commit message
- [x] Push your changes to your fork, create a PR, get merged, celebrate ??

We are happy to support you if you need help.

**Comment by abikaram** [comment]
Hello. This is my first time contributing to open source. Is this issue still open?

**Comment by thomas694** [comment]
Hello,
thanks for your interest. Yes, it's still open. I'll assign it to you.
If you have a question or get stuck, feel free to ask.

**Comment by abikaram** [comment]
Sorry I haven't updated you in a while, I'm having a bit of trouble understanding this. Should I alter the Files.cs class or do I just add to CrawlAsync() right before DownloadCrawlerDataAsync()?

**Comment by thomas694** [comment]
It depends on the solution that you think about. But I think there aren't any changes necessary in the Files class. Your second mention is maybe the right direction.

**Comment by thomas694** [comment]
Hello,
does your idea work? Are you stuck?

**Comment by thomas694** [comment]
Any news? Any questions?

**Comment by thomas694** [comment]
This issue is available again for new volunteers.

**Comment by thomas694** [comment]
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.
