### ISSUE TITLE
Plenty System.NotImplementedExceptions

### ISSUE THREAD

**Issue by thomas694** [TumblThreeApp/TumblThree#99]
**Describe the bug/problem**
While crawling a few blogs dozens of System.NotImplementedExceptions are showing up in Visual Studio's log window. But all files seem to be downloaded.

**To Reproduce**
1. Run TumblThree from Visual Studio
2. Crawl one or more blogs
3. Inspect the blog's folder
4. Watch the Immediate Window

**Expected behavior**
If there are no real problems and the files are downloaded, there shouldn't be so much exceptions showing up.

**Desktop (please complete the following information):**
 - TumblThree version: 1.0.11.12
 - OS: Win 10

Does anyone know how to track these exceptions and to find its source? Can you solve it?

**Comment by thomas694** [comment]
[As before](https://github.com/TumblThreeApp/TumblThree/issues/100) this one is for first-timers-only. That means that we will only accept a PR for this one from someone who's never contributed to open source before. This one is particularly easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). We walk you through it if you need help. :-) Here are the steps to get a PR merged here (see also our [wiki](https://github.com/TumblThreeApp/TumblThree/blob/master/docs/Contributing.md)).

- [x] Create a fork of the repository
- [x] Clone it to your local disk and create a new branch (e.g. 99-fix-notimplementedexceptions)
- [x] Build the app and run it in debug mode of VS
- [x] Add a few blogs and download them, inspect the VS log/immediate window while downloading the blogs, and recognize the plenty NotImplementedExceptions thrown
- [x] Find out how this uncaught exceptions can be inspected with *reconfigured* VS
- [x] You should come to a method inside [TumblrJsonDownloader.cs](https://github.com/TumblThreeApp/TumblThree/blob/ce7a675a9e2a74ab135ed24b72b6653567ec0f43/src/TumblThree/TumblThree.Applications/Downloader/TumblrJsonDownloader.cs)
- [x] Find out why VS debugger breaks on that line. Read the MS documentation for the used method, also try to find/google the MS source code of that method from the "equivalent" .net core framework to get an idea
- [x] For an async method you normally await another async method. So the original author used the found method, because its one of the rare async methods available in that class
- [x] Find an alternative for this exception throwing line, look for its necessity, other async methods and *default tasks*
- [x] Commit your changes mentioning "issue #99" in the commit message
- [x] Push your changes to your fork, create a PR, get merged, celebrate ??

We are happy to support you if you need help.

**Comment by MaxNau** [comment]
Hi,

this is still relevant? I haven't seen any System.NotImplementedExceptions in the VS log, but I saw a lot of System.IO.IOException "The process cannot access the file 'file path' because it is being used by another process".

**Comment by thomas694** [comment]
Hi,
yes, it's still there. You have to enable the options "Dump crawler data" and "Metadata format: JSON" in the blog's settings.
And yes, you just found another problem in the area of dumping crawler data. But that's not necessarily part of this issue.

**Comment by thomas694** [comment]
Thanks for your first contribution and PR to open source, and especially to the TumblThree project.
Your PR has been merged and you've been added to our list of contributors.
You are welcome to solve some more issue (not first-timers-only).
